apigee/registry

.github/workflows/go.yml
unzip seems to be already installed in the base image.
=> Simplify CI

cmd/registry/cmd/upload-bulk-openapi.go
The refactoring and functional changes are included in separate commits and might be easiest to review if viewed separately.
=> Refactor + Support revisions for OpenAPI bulk upload command

server/actions_apis.go, server/actions_specs.go, server/actions_versions.go, server/filters.go, server/models/api.go, server/models/spec.go, server/models/version.go, tests/filters_test.go
The first commit is for APIs only. Let's give that an initial review before adding version and spec filtering.
=> Add label-based filtering to apis, versions, and specs.

cmd/registry-graphql/graphql/graphql_test.go, server/actions_projects.go, server/actions_projects_test.go, tests/crud/crud_test.go, tests/demo/demo_test.go, tests/filters_test.go
Some tests are marked as skipped until larger changes are submitted to make them pass.
=> Projects testing + Handler updates

server/actions_versions.go, server/actions_versions_test.go
* Support filtering by version resource name
* Return NOT_FOUND when deleting nonexistent resources
* Return INVALID_ARGUMENT on negative page size
* Return INVALID_ARGUMENT on invalid page token
* Add server tests for version actions
=> Versions Testing + Updates

tests/demo/demo_test.go
This test is currently causing flakiness due to lack of ordering by
SQLite database used for testing. When fully supported this change can
be reversed.
=> Skip test for ListApiSpecRevision ordering

.github/workflows/go.yml, server/actions_apis.go, server/actions_apis_test.go, server/actions_projects.go, server/actions_projects_test.go, server/actions_spec_revisions.go, server/actions_spec_revisions_test.go, server/actions_specs.go, server/actions_specs_test.go, server/actions_status_test.go, server/actions_versions.go, server/actions_versions_test.go, server/datastore/deletions.go, server/errors.go, server/gorm/deletions.go, server/gorm/gorm_test.go, server/gorm/iterator.go, server/models/api.go, server/models/project.go, server/models/spec.go, server/models/version.go, server/names/api.go, server/names/common.go, server/names/project.go, server/names/spec.go, server/names/spec_revision.go, server/names/version.go, server/storage/storage.go, tests/demo/demo_test.go, tests/filters_test.go
This branch includes incrementally reviewed changes that introduce a suite of unit tests for the server. Along with the tests, some bug fixes are included for some situations that tests detected an issue and could be easily resolved. Other known bugs have their tests marked as skipped until they can be addressed on the main branch.
=> Core API Test Suite + Bug Fixes

server/server.go
When the storage client cannot be created without error it results in
RPC handlers returning unavailable status. When that happens, apg and
other clients try again until timeout is reached. This change logs the
error when it occurs so developers are informed of their environment
problem. Previously the request would appear to hang.
=> Add logging for GCP project errors

server/actions_artifacts.go, server/actions_artifacts_test.go, server/dao/artifacts.go, server/dao/specs.go, server/datastore/deletions.go, server/gorm/deletions.go, server/models/artifact.go, server/models/blob.go, server/models/spec.go, server/models/version.go, server/names/api.go, server/names/artifact.go, server/names/project.go, server/names/spec.go, server/names/version.go, server/storage/storage.go
* Move model storage code into DAO
* Use names package for parsing and representing resource names
* Add test suite
=> Refactor Artifacts service

server/models/spec.go
Fixes #50 in the case where contents are included in the update mask.
=> Do not change spec create time on update

server/dao/specs.go
=> Add missing spec filter fields

server/gorm/client.go, server/gorm/gorm_test.go
=> Write all fields including zero-value in gorm

cmd/registry/core/projects.go, google/cloud/apigee/registry/v1/registry_service.proto, server/actions_apis_test.go, server/actions_artifacts.go, server/actions_artifacts_test.go, server/actions_projects_test.go, server/actions_spec_revisions.go, server/actions_specs_test.go, server/actions_versions_test.go, server/names/api.go, server/names/artifact.go, server/names/common.go, server/names/names_test.go, server/names/project.go, server/names/spec.go, server/names/version.go
=> Expand validation for resource IDs and tags

google/cloud/apigee/registry/v1/registry_service.proto, openapi.yaml, server/actions_apis_test.go, server/actions_artifacts_test.go, server/actions_projects_test.go, server/actions_specs_test.go, server/actions_versions_test.go, server/names/common.go
Addresses a problem noted in #150
=> Increase the identifier length limit to 80.

cmd/control_loop/controller/controller.go, cmd/control_loop/controller/controller_test.go, cmd/control_loop/controller/manifest_reader.go, cmd/control_loop/controller/parser.go, cmd/control_loop/list/apis.go, cmd/control_loop/list/artifacts.go, cmd/control_loop/list/list.go, cmd/control_loop/list/specs.go, cmd/control_loop/main.go, cmd/control_loop/manifest.yaml, cmd/control_loop/resources/resources.go, cmd/control_loop/test/manifest_1.yaml, go.mod, go.sum
This is the initial implementation of the controller. 
Other follow up items will come in subsequent PRs:
* refactoring
*  adding more test cases
* Migrating the command to the cobra framework
=> Initial controller

cmd/control_loop/controller/controller_test.go, cmd/control_loop/test/manifest_2.yaml, cmd/control_loop/test/manifest_3.yaml
Summary of changes:
- Added more tests for controller.go
- Got rid of `check()` and `readAndGZipFile()`
=> Additional tests for controller

cmd/registry/cmd/bleve.go, cmd/registry/cmd/compute-complexity.go, cmd/registry/cmd/compute-descriptor.go, cmd/registry/cmd/compute-details.go, cmd/registry/cmd/compute-index.go, cmd/registry/cmd/compute-lint.go, cmd/registry/cmd/compute-references.go, cmd/registry/cmd/compute-vocabulary.go, cmd/registry/cmd/count-versions.go, cmd/registry/cmd/delete.go, cmd/registry/cmd/label.go, cmd/registry/cmd/upload-bulk-discovery.go, cmd/registry/cmd/upload-bulk-openapi.go, cmd/registry/cmd/upload-bulk-protos.go, cmd/registry/core/tasks.go
=> Rename "Name()" to "String()" in Task interface.

cmd/control_loop/controller/controller.go, cmd/control_loop/controller/parser.go
Summary of my changes:
* Got rid of the dependency on reflect package
* Refactored parser.go to make it more readable, added examples in comments
* Added more logging and error handling in controller.go
=> Refactor parser.go and controller.go

cmd/registry/cmd/upload-csv.go, cmd/registry/cmd/upload-csv_test.go, tests/seeding/fileseed/fileseed.go, tests/seeding/fileseed/fileseed_test.go
* Add file seeding package to test directory
=> Add CSV import command to registry tool

server/actions_specs.go, server/actions_specs_test.go
* Return invalid argument if the /contents suffix is not provided.
* Return failed precondition if the mime type indicates gzip but gzip
fails to decompress the spec contents.
Fixes #176, Fixes #177.
=> Expand error handling for GetApiSpecContents

cmd/control_loop/controller/controller.go, cmd/control_loop/controller/parser.go
Refactored the usage of pointers in `controller.go`
=> Revisit pointers in controller.go

google/cloud/apigee/registry/applications/v1alpha1/registry_manifest.proto
Initial proto definition for controller manifest.
=> Proto definition for manifest

cmd/registry-graphql/graphql/graphql_test.go, server/actions_apis_test.go, server/actions_artifacts_test.go, server/actions_projects_test.go, server/actions_spec_revisions_test.go, server/actions_specs_test.go, server/actions_versions_test.go, server/dao/apis.go, server/dao/artifacts.go, server/dao/projects.go, server/dao/specs.go, server/dao/versions.go
=> Return next_page_token only if another page is known to exist

go.mod, go.sum, server/gorm/deletions.go
=> Delete children artifacts when ancestor is deleted

.github/workflows/go.yml, server/server_test.go
=> Add server testing with PostgreSQL

cmd/capabilities/testdata/openapi.yaml, cmd/registry/breaking-change-detector/breaking_change_detector.go, cmd/registry/breaking-change-detector/breaking_change_detector_test.go, cmd/registry/cmd/resolve/testdata/openapi.yaml, cmd/registry/cmd/root_test.go, cmd/registry/cmd/upload/testdata/cloudtasks/v2/openapi.yaml, cmd/registry/cmd/upload/testdata/cloudtasks/v2beta2/openapi.yaml, cmd/registry/cmd/upload/testdata/datastore/v1/openapi.yaml, cmd/registry/cmd/upload/testdata/datastore/v1beta1/openapi.yaml, cmd/registry/controller/local-tasks.go, cmd/registry/controller/local-tasks_test.go, cmd/registry/diff/differ.go, cmd/registry/diff/differ_test.go, cmd/registry/diff/test-specs/base-test.yaml, cmd/registry/diff/test-specs/struct-test-add.yaml, cmd/registry/diff/test-specs/struct-test-delete.yaml, cmd/registry/diff/test-specs/struct-test-modify.yaml, cmd/registry/diff/test-specs/struct-test-order.yaml, google/cloud/apigee/registry/applications/v1alpha1/diff_analytics.proto, tests/crud/testdata/openapi.yaml
Add tests to secure the [switch case block](https://github.com/apigee/registry/blob/68e0507f798395bab574ed4b5a90db4e0cdc8cb0/cmd/registry/controller/local-tasks.go#L41) in `controller/local-tasks.go`
=> Add tests to validate command coverage in controller/local-tasks.go

cmd/registry/cmd/resolve/resolve_test.go, cmd/registry/cmd/root_test.go, cmd/registry/controller/local-tasks.go, cmd/registry/controller/local-tasks_test.go
Move ExecCommandTask back to using exec.Command()
=> Switch resolve command back to multi-process

Makefile, cmd/registry/metrics/metrics.go, cmd/registry/metrics/metrics_test.go, containers/registry-tools/registry-linters/Dockerfile, deployments/gke-job/cron-job.yaml
Add config for GKE cron job 
This job runs the `resolve` command every 5 mins
Add a registry-linters container which is used by the GKE job.
=> Add basic config for registry cron job

cmd/registry/cmd/resolve/resolve.go, cmd/registry/cmd/root_test.go, cmd/registry/controller/controller.go, cmd/registry/controller/controller_test.go, cmd/registry/controller/local-tasks.go, cmd/registry/controller/local-tasks_test.go, google/cloud/apigee/registry/applications/v1alpha1/registry_manifest.proto, google/cloud/apigee/registry/applications/v1alpha1/registry_receipt.proto, tools/COMPILE-PROTOS.sh
Summary of changes:
* Renamed flag `placeholder` to `receipt` https://github.com/apigee/registry/issues/276
* Define a proto for ReceiptArtifact https://github.com/apigee/registry/issues/274
=> Rename flag 'placeholder' to 'receipt' and define a proto

cmd/registry/controller/controller.go, cmd/registry/controller/parser.go, cmd/registry/controller/parser_test.go
=> Parser tests

cmd/registry/cmd/compute/conformance.go, cmd/registry/cmd/export/sheet.go, cmd/registry/cmd/resolve/resolve.go, cmd/registry/cmd/upload/csv.go, cmd/registry/controller/controller.go, cmd/registry/controller/local-tasks.go, cmd/registry/core/details-proto.go, cmd/registry/core/lint-proto.go, cmd/registry/core/projects.go, cmd/registry/core/specs.go, cmd/registry/core/tasks.go, cmd/registry/core/yaml.go, cmd/registry/core/zip.go, cmd/registry/googleauth/client.go
* Use structured logging
* Replace unchecked errors with explicit discard
* Use `UpdateApiSpec` with `allow_missing` flag in `core/specs.go`
* Formatting adjustments
=>  Use structured logging in cmd/registry packages

cmd/registry/plugins/registry-lint-api-linter/main.go, cmd/registry/plugins/registry-lint-api-linter/main_test.go, cmd/registry/plugins/registry-lint-spectral/main.go, cmd/registry/plugins/registry-lint-spectral/main_test.go
This addresses the comment left on: https://github.com/apigee/registry/pull/387#discussion_r745184209
=> Use a function pointer in place of a struct with Execute() function

server/registry/actions_artifacts.go, server/registry/actions_artifacts_test.go, server/registry/internal/storage/artifacts.go
This adds the ability to list artifacts that belong to deployments and verifies that deployments exist when artifacts are created. Thanks @krpate for finding these problems!
=> List deployment artifacts

cmd/registry/cmd/get/get.go, cmd/registry/cmd/list/list.go, cmd/registry/core/get.go, cmd/registry/core/handlers.go, cmd/registry/core/list.go, cmd/registry/core/print.go, server/registry/internal/storage/deployments.go, server/registry/internal/storage/models/blob.go
This adds missing deployment-related features to the registry tool and fixes a "leak" of artifact blobs that were not being deleted with their associated deployments.
=> Improve listing and deletion of deployments and related artifacts

server/registry/internal/storage/list.go
=> Return errors from database listing operations

server/registry/internal/storage/get.go, server/registry/internal/storage/tag.go
Hey, I saw issue #442 and wanted to fix this issue.
=> Change First queries in GORM to Take for performance purposes

containers/registry-server/Dockerfile
Sync docker files from the hosted version
=> Build registry controller ghcr.io image

cmd/registry/core/list.go
=> Fix filtering overwrite bug in listing helpers

cmd/registry/cmd/upload/artifact.go, cmd/registry/cmd/upload/manifest.go, cmd/registry/controller/controller.go, cmd/registry/controller/controller_test.go, cmd/registry/controller/list.go, cmd/registry/controller/parser.go, cmd/registry/controller/parser_test.go, cmd/registry/controller/resource-name.go, cmd/registry/controller/resource.go, cmd/registry/controller/test_helpers.go
Fixes: https://github.com/apigee/registry/issues/464
=> Update manifest validate function to support advanced patterns

server/registry/actions_deployment_revisions_test.go, server/registry/actions_spec_revisions_test.go, server/registry/internal/storage/list.go
=> Support listing revisions across collections

README.md, cmd/registry/APIHUB-README.md, demos/disco.sh, demos/openapi.sh, demos/protos.sh, deployments/envoy/README.md, deployments/gke/README.md, tests/controller/README.md, tests/controller/demo.sh, tools/GENERATE-APG.sh, tools/GENERATE-DOCS.sh, tools/GENERATE-ENVOY-DESCRIPTORS.sh, tools/GENERATE-GAPIC.sh, tools/GENERATE-GRPC.sh, tools/GENERATE-OPENAPI.sh, tools/GENERATE-RPC.sh, tools/LINT-PROTOS.sh, tools/PROTOC-VERSION.sh, tools/PROTOS.sh
=> use `.` instead of `source` in scripting

cmd/registry/APIHUB-README.md
Let's run `./tools/pretty.sh` to automatically format any edits to markdown files.
=> Format APIHUB-README.md with ./tools/pretty.sh

cmd/registry/patch/api.go, cmd/registry/patch/project.go
Previously we were returning errors for these artifacts, which was breaking export altogether. Now we skip them. In the future, we might find some other way to serialize them. Fixes #578.
=> Skip non-yaml artifacts in YAML export.

.codecov.yml
ignore generated files
set yellow range to 75-90
see #606
=> adjust codecov config

cmd/registry/diff/differ.go, cmd/registry/diff/differ_test.go, cmd/registry/patterns/parser.go, cmd/registry/patterns/resources.go, examples/pubsub/publish/main.go, gapic/admin_client.go, gapic/doc.go, gapic/provisioning_client.go, gapic/registry_client.go, google/cloud/apigeeregistry/applications/v1alpha1/diff_analytics.proto, tools/GENERATE-CLI.sh, tools/GENERATE-GAPIC.sh
=> fix formatting and misspellings

cmd/registry/cmd/resolve/resolve.go
Add --jobs flag to limit the number of workers in the controller.
=> Add --jobs flag in the controller

cmd/registry/cmd/auth/auth.go, cmd/registry/cmd/auth/print_token.go, cmd/registry/cmd/config/config.go, cmd/registry/cmd/config/configurations/configurations.go, cmd/registry/cmd/config/configurations/create.go, cmd/registry/cmd/config/get.go, cmd/registry/cmd/config/list.go, cmd/registry/cmd/config/set.go, cmd/registry/cmd/config/unset.go
=> Add documentation to config and auth commands

server/registry/actions_spec_revisions.go, server/registry/actions_spec_revisions_test.go, server/registry/internal/storage/delete.go
=> disallow delete of only SpecRevision

server/registry/actions_artifacts.go, server/registry/actions_artifacts_test.go, server/registry/actions_deployments.go, server/registry/actions_deployments_test.go, server/registry/actions_specs.go, server/registry/actions_specs_test.go, server/registry/internal/storage/create.go, server/registry/internal/storage/save.go
=> improve create entity validation and efficiency

auth/HOSTED.bat
Ticket #701 This has been tested using https://github.com/giteshk-org/registry/releases/tag/v0.3.21
=> #701 Update windows auth file to use registry configurations

cmd/registry/plugins/registry-lint-spectral/main.go
Fixes https://github.com/apigee/registry/issues/709
=> Remove check for specName while performing linting

cmd/registry/cmd/resolve/resolve.go, cmd/registry/controller/controller-timestamp_test.go, cmd/registry/controller/controller.go, cmd/registry/controller/controller_test.go
The default value is `100` for now, it is subject to change once we do some testing while deploying it to the data plane.
=> Support max-actions flag in resolve

server/registry/internal/storage/errors.go
As mentioned [here](https://github.com/apigee/registry/pull/700#discussion_r959012325), this adds handling of errors that appeared during load testing.
=> Add handlers for more possible errors that can arise during load-testing

server/registry/actions_deployment_revisions_test.go, server/registry/internal/storage/delete.go
addresses #717, follows the pattern in #698
=> prevent deletion of the only deployment revision

cmd/registry/cmd/upload/csv.go
=> fix csv version path

server/registry/actions_apis.go, server/registry/actions_artifacts.go, server/registry/actions_deployment_revisions.go, server/registry/actions_deployments.go, server/registry/actions_projects.go, server/registry/actions_spec_revisions.go, server/registry/actions_specs.go, server/registry/actions_versions.go, server/registry/internal/storage/delete.go
=> remove extra db query in delete

cmd/registry/cmd/auth/print_token.go, cmd/registry/cmd/config/get.go, cmd/registry/cmd/config/list.go, cmd/registry/cmd/config/set.go, cmd/registry/cmd/config/unset.go, pkg/config/config.go, pkg/config/configuration_test.go
=> fix error variable names

auth/LOCAL.sh
=> remove unnecessary code

server/registry/internal/storage/errors.go
=> stack trace should be debugf

.github/workflows/release.yml, containers/registry-tools/Dockerfile
Added spectral and api-linter plugin to registry-tools
Binaries for api-linter and spectral will be added to the registry-linters image
=> Added spectral lint executables to registry-tools

.github/workflows/release.yml
=> Issue #575: Use the latest version of GoReleaser

server/registry/actions_apis.go, server/registry/actions_apis_test.go, server/registry/actions_projects.go, server/registry/actions_projects_test.go, server/registry/actions_versions.go, server/registry/actions_versions_test.go, server/registry/internal/storage/save.go
This appears to resolve #795.
New tests mimic the script in #795 that was used to isolate the problem.
=> Revert #742, add tests to detect future regressions

cmd/registry/cmd/compute/score.go, cmd/registry/scoring/score.go, cmd/registry/scoring/scorecard.go
Fixes https://github.com/apigee/registry/issues/798
=> Gracefully handle unmatched score definitions

server/registry/internal/storage/client.go
=> ensure SQLite doesn't lose foreign key contraint

cmd/registry/scoring/parser.go
This PR is a follow-up for this comment: https://github.com/apigee/registry/pull/806#discussion_r1015880172
Missed addressing it in the original PR.
=> Follow up on clearing up the if conditions

server/registry/internal/storage/list.go
=> reuse latestDeploymentRevisionsQuery

.github/workflows/go.yml
=> fix test on postgres 15

server/registry/actions_apis_test.go, server/registry/internal/storage/list.go
=> ensure filtering honors requested page size

log/interceptor/interceptor.go
=> Update field name for parent resource in logs

server/registry/actions_artifacts_test.go, server/registry/internal/storage/get.go
=> get deployment artifacts and contents

cmd/registry/types/types_test.go
=> Add tests for types package

cmd/registry/cmd/annotate/annotate.go, cmd/registry/cmd/compute/complexity.go, cmd/registry/cmd/compute/conformance.go, cmd/registry/cmd/compute/lint.go, cmd/registry/cmd/compute/lintstats.go, cmd/registry/cmd/compute/vocabulary.go, cmd/registry/cmd/count/revisions.go, cmd/registry/cmd/delete/delete.go, cmd/registry/cmd/export/csv.go, cmd/registry/cmd/label/label.go, cmd/registry/cmd/list/list.go, cmd/registry/controller/list.go, cmd/registry/core/list.go, cmd/registry/patch/project.go, cmd/registry/patch/version.go, cmd/registry/patterns/resources.go
=> add getContents flag to ListSpecs and ListSpecRevisions

cmd/registry/cmd/export/csv_test.go, cmd/registry/cmd/export/yaml_test.go
=> Remove calls to deprecated SetOutput method

server/registry/actions_artifacts_test.go, server/registry/internal/storage/list.go
=> return missing when list artifacts missing parent

cmd/registry/cmd/check/rules/rule103/rule103.go, cmd/registry/cmd/check/rules/rule103/rule103_test.go, cmd/registry/cmd/check/rules/rule104/rule104.go, cmd/registry/cmd/check/rules/rule104/rule104_test.go, cmd/registry/cmd/check/rules/rules.go
=> add registry rules for ApiVersion

cmd/registry/cmd/check/rules/rule105/rule105.go, cmd/registry/cmd/check/rules/rule105/rule105_test.go, cmd/registry/cmd/check/rules/rules.go
=> add registry rules for ApiSpec

server/registry/actions_deployment_revisions_test.go, server/registry/actions_spec_revisions_test.go, server/registry/internal/storage/list.go
=> remove implicit current revision from list APIs

cmd/registry/cmd/check/rules/rule106/rule106.go, cmd/registry/cmd/check/rules/rule106/rule106_test.go, cmd/registry/cmd/check/rules/rule107/rule107.go, cmd/registry/cmd/check/rules/rule107/rule107_test.go, cmd/registry/cmd/check/rules/rule108/rule108.go, cmd/registry/cmd/check/rules/rule108/rule108_test.go, cmd/registry/cmd/check/rules/rules.go, cmd/registry/cmd/check/rules/util/uri.go, cmd/registry/cmd/check/rules/util/uri_test.go
=> add registry rules for ApiDeployment

cmd/registry/cmd/root_test.go
This adds an optional addition to the command tests that logs any leaf-level commands that lack pages on the [registry wiki](https://github.com/apigee/registry/wiki). These checks are only made when the `-github` flag is include, e.g.
```
go test ./cmd/registry/cmd -v -github
```
By default, checks are not made. This is to avoid overusing GitHub queries during automated testing and because this is an expectation that could be open to some debate. The goal of this PR is just to start measuring which leaf-level commands lack pages with corresponding names (one page per command). Currently we get the following results:
```
$ go test ./cmd/registry/cmd  -v -github
=== RUN   TestCommandMetadata
=== RUN   TestCommandMetadata/registry
=== RUN   TestCommandMetadata/registry_annotate …
```
=> Add optional test that looks for wiki pages for leaf-level commands.

google/cloud/apigeeregistry/v1/registry_models.proto, rpc/registry_models.pb.go
=> labels and annotations docs

cmd/registry/cmd/check/rules/rule109/rule109.go, cmd/registry/cmd/check/rules/rule109/rule109_test.go, cmd/registry/cmd/check/rules/rule110/rule110_test.go, cmd/registry/cmd/check/rules/rule111/rule111.go, cmd/registry/cmd/check/rules/rule111/rule111_test.go, cmd/registry/cmd/check/rules/rule112/rule112.go, cmd/registry/cmd/check/rules/rule112/rule112_test.go, cmd/registry/cmd/check/rules/rule113/rule113.go, cmd/registry/cmd/check/rules/rule113/rule113_test.go, cmd/registry/cmd/check/rules/rules.go, cmd/registry/cmd/check/rules/util/strings.go, cmd/registry/cmd/check/rules/util/strings_test.go
=> add registry rules for fields

cmd/registry/cmd/check/tree/tree.go, cmd/registry/cmd/compute/lintstats/lintstats.go, cmd/registry/cmd/delete/delete.go, cmd/registry/cmd/export/export.go, cmd/registry/cmd/get/get.go, cmd/registry/patch/patch_test.go, pkg/visitor/get.go, pkg/visitor/list.go, pkg/visitor/visit.go
allow an implicit project to be visited with ListProjects 
also renames allowUnavailable to implicitProject
=> allow an implicit project to be visited with ListProjects 

cmd/registry/cmd/check/check.go, cmd/registry/cmd/check/lint/checker_test.go, cmd/registry/cmd/check/lint/config.go, cmd/registry/cmd/check/lint/rule_groups.go, cmd/registry/cmd/check/lint/rule_groups_test.go, cmd/registry/cmd/check/tree/tree.go
improve check:
- rename "hub" rule group to "apihub"
- disable apihub and score rules by default
- add --enable --disable rules on CLI
- fix implicit project name in tree
=> check improvements

cmd/registry/cmd/check/lint/rule.go, cmd/registry/cmd/check/rules/rule1000/rule1000.go, cmd/registry/cmd/check/rules/rule1000/rule1000_test.go, cmd/registry/cmd/check/rules/rule1001/rule1001.go, cmd/registry/cmd/check/rules/rule1001/rule1001_test.go, cmd/registry/cmd/check/rules/rule1002/rule1002.go, cmd/registry/cmd/check/rules/rule1002/rule1002_test.go, cmd/registry/cmd/check/rules/rules.go, pkg/connection/grpctest/server.go, server/registry/names/artifact.go, server/registry/names/common.go, server/registry/names/project.go
=> add registry rules for API Hub

cmd/registry/cmd/get/get.go, cmd/registry/cmd/get/get_test.go
=> Add --nested flag to `registry get`

cmd/registry/cmd/export/export.go, cmd/registry/cmd/get/get.go
=> Remove context fields from structs and use new handler interface.

cmd/registry/cmd/delete/delete.go
=> Collect and then delete resources to work around problems listing-while-deleting.

cmd/registry/cmd/check/check.go
=> check `--list-rules` option

cmd/registry/cmd/check/rules/rule1000/rule1000.go, cmd/registry/cmd/check/rules/rule1000/rule1000_test.go, cmd/registry/cmd/check/rules/rule1001/rule1001_test.go, cmd/registry/cmd/check/rules/rule1002/rule1002.go, cmd/registry/cmd/compute/complexity/complexity.go, cmd/registry/cmd/compute/conformance/conformance.go, cmd/registry/cmd/compute/lint/lint.go, cmd/registry/cmd/compute/lintstats/lintstats.go, cmd/registry/cmd/compute/vocabulary/vocabulary.go, cmd/registry/cmd/delete/delete_test.go, cmd/registry/cmd/diff/diff.go, cmd/registry/cmd/get/get_test.go, cmd/registry/cmd/upload/csv.go, cmd/registry/cmd/upload/discovery.go, cmd/registry/cmd/upload/openapi.go, cmd/registry/cmd/upload/protos.go, cmd/registry/cmd/vocabulary/vocabulary.go, cmd/registry/conformance/conformance-task.go, cmd/registry/controller/controller_test.go, cmd/registry/controller/local-tasks.go, cmd/registry/patch/artifact.go, cmd/registry/patch/patch_test.go, cmd/registry/scoring/expression.go, cmd/registry/scoring/score.go, cmd/registry/scoring/scorecard.go, pkg/mime/types.go, pkg/mime/types_test.go
=> Move pkg/types to pkg/mime

.github/workflows/release.yml
=> Set RELEASE_VERSION in release action.

cmd/registry/cmd/apply/apply.go, cmd/registry/cmd/check/check.go, cmd/registry/cmd/compute/complexity/complexity.go, cmd/registry/cmd/compute/conformance/conformance.go, cmd/registry/cmd/compute/lint/lint.go, cmd/registry/cmd/compute/lintstats/lintstats.go, cmd/registry/cmd/compute/score/score.go, cmd/registry/cmd/compute/scorecard/scorecard.go, cmd/registry/cmd/compute/vocabulary/vocabulary.go, cmd/registry/cmd/config/configurations/activate.go, cmd/registry/cmd/config/configurations/create.go, cmd/registry/cmd/config/configurations/delete.go, cmd/registry/cmd/config/configurations/describe.go, cmd/registry/cmd/diff/diff.go, cmd/registry/cmd/resolve/resolve.go, cmd/registry/cmd/upload/openapi.go, cmd/registry/cmd/upload/protos.go
=> ensure cmd use documents positional args

cmd/registry/cmd/config/get.go, pkg/config/configuration.go, pkg/config/configuration_test.go
=> add default namespace "registry" to config props

cmd/registry/cmd/compute/score/score.go, cmd/registry/cmd/compute/scorecard/scorecard.go
=> resolve name for compute score / scorecard

cmd/registry/patch/apply.go
=> report which file had error

cmd/registry/cmd/auth/print_token.go, cmd/registry/cmd/check/rules/rule1000/rule1000.go, cmd/registry/cmd/config/config_test.go, cmd/registry/cmd/config/configurations/activate.go, cmd/registry/cmd/config/configurations/configurations_test.go, cmd/registry/cmd/config/configurations/create.go, cmd/registry/cmd/config/configurations/delete.go, cmd/registry/cmd/config/configurations/describe.go, cmd/registry/cmd/config/configurations/list.go, cmd/registry/cmd/config/get.go, cmd/registry/cmd/config/list.go, cmd/registry/cmd/config/set.go, cmd/registry/cmd/config/unset.go, cmd/registry/cmd/upload/discovery.go, cmd/registry/cmd/upload/openapi.go, cmd/registry/cmd/upload/protos.go, cmd/registry/conformance/conformance-task.go, cmd/registry/conformance/linter.go, cmd/registry/controller/controller.go, cmd/registry/patterns/parser.go, cmd/registry/scoring/parser.go, pkg/config/config.go, pkg/config/configuration.go, pkg/names/common.go
addresses all non-generated linter errors for #744
=> address staticcheck lint errors

cmd/registry/cmd/upload/csv.go, cmd/registry/cmd/upload/csv_test.go, cmd/registry/cmd/upload/testdata/csv/multiple-specs.csv
=> derive and encode openapi version in mimetype

cmd/registry/cmd/apply/apply_test.go, cmd/registry/cmd/auth/print_token.go, cmd/registry/cmd/config/config.go, cmd/registry/cmd/config/config_test.go, cmd/registry/cmd/config/configurations/activate.go, cmd/registry/cmd/config/configurations/create.go, cmd/registry/cmd/config/configurations/delete.go, cmd/registry/cmd/config/configurations/describe.go, cmd/registry/cmd/config/configurations/list.go, cmd/registry/cmd/config/get.go, cmd/registry/cmd/config/list.go, cmd/registry/cmd/config/set.go, cmd/registry/cmd/config/unset.go, cmd/registry/cmd/delete/delete_test.go, cmd/registry/cmd/get/get_test.go, pkg/config/config.go, pkg/config/configuration.go
=> enable usage and error messages, minor refactoring

pkg/visitor/content.go, pkg/visitor/content_test.go
This follows [`visitor.FetchSpecContents()`](https://github.com/apigee/registry/blob/6781b6939b74bc960757218b68d319b4bed3d012/pkg/visitor/fetch.go#L32) in accepting spec contents as gzipped when available, but because callers expect uncompressed bytes, it also uncompresses them. It fixes problems that appear when callers try to work on specs that are over message size limits when uncompressed.
Arguably, one of `GetBytesForSpec()` and `FetchSpecContents()` should be eliminated.
#1110 for general discussion of content sizes.
=> Accept gzip-encoded content in GetBytesForSpec()

cmd/registry/cmd/annotate/annotate.go, cmd/registry/cmd/check/lint/checker.go, cmd/registry/cmd/compute/complexity/complexity.go, cmd/registry/cmd/compute/conformance/conformance.go, cmd/registry/cmd/compute/lint/lint.go, cmd/registry/cmd/compute/score/score.go, cmd/registry/cmd/compute/scorecard/scorecard.go, cmd/registry/cmd/compute/vocabulary/vocabulary.go, cmd/registry/cmd/delete/delete.go, cmd/registry/cmd/export/export.go, cmd/registry/cmd/label/label.go, cmd/registry/cmd/resolve/resolve.go, cmd/registry/cmd/upload/csv.go, cmd/registry/cmd/upload/discovery.go, cmd/registry/cmd/upload/openapi.go, cmd/registry/cmd/upload/protos.go, cmd/registry/patch/apply.go, cmd/registry/patch/export_test.go, cmd/registry/tasks/tasks.go, cmd/registry/tasks/tasks_test.go, go.mod, pkg/wipeout/wipeout.go, tests/benchmark/benchmark_artifacts_test.go
=> return task error from WorkerPool

cmd/registry/tasks/tasks.go, cmd/registry/tasks/tasks_test.go
=> add continueOnError param to WorkerPool

pkg/config/configuration.go
=> quick fix to report failures from running the token-source.

rpc/admin_service.pb.go, rpc/admin_service_grpc.pb.go, rpc/provisioning_service.pb.go, rpc/provisioning_service_grpc.pb.go
=> Update dependency on longrunning protos (by rerunning code generators)

cmd/registry/cmd/annotate/annotate.go, cmd/registry/cmd/compute/complexity/complexity.go, cmd/registry/cmd/compute/conformance/conformance.go, cmd/registry/cmd/compute/lintstats/lintstats.go, cmd/registry/cmd/compute/score/score.go, cmd/registry/cmd/compute/scorecard/scorecard.go, cmd/registry/cmd/compute/vocabulary/vocabulary.go, cmd/registry/cmd/diff/diff.go, cmd/registry/cmd/label/label.go, cmd/registry/cmd/resolve/resolve.go
=> Convert remaining Cobra Run: instances to RunE:

cmd/registry/cmd/check/rules/rule105/rule105.go, cmd/registry/cmd/check/rules/rule109/rule109.go, cmd/registry/cmd/check/rules/rule109/rule109_test.go, cmd/registry/cmd/check/rules/rule112/rule112.go, cmd/registry/cmd/check/rules/rule112/rule112_test.go, cmd/registry/cmd/check/rules/rule113/rule113.go, cmd/registry/cmd/check/rules/rule113/rule113_test.go, cmd/registry/cmd/check/rules/rules.go
These were issues I found in the rules when I was documenting all the rules in the wiki. https://github.com/apigee/registry/wiki/registry-check-and-rules
=> fix differences from rules audit

containers/registry-server/Dockerfile
=> enable CGO for sqlite3

cmd/registry/cmd/resolve/resolve.go
=> deprecate --max-actions in favor of --actions

cmd/registry/cmd/check/rules/rule101/rule101_test.go, cmd/registry/cmd/check/rules/rule102/rule102_test.go, cmd/registry/cmd/check/rules/rule104/rule104_test.go, cmd/registry/cmd/check/rules/rule106/rule106_test.go, pkg/names/common.go, server/registry/actions_apis_test.go, server/registry/actions_artifacts_test.go, server/registry/actions_deployments_test.go, server/registry/actions_projects_test.go, server/registry/actions_specs_test.go, server/registry/actions_versions_test.go
=> names must be lowercase

cmd/registry/cmd/apply/apply.go, cmd/registry/patch/apply.go, cmd/registry/patch/export_test.go, cmd/registry/patch/patch_lists_test.go, cmd/registry/patch/patch_project_test.go, cmd/registry/patch/patch_test.go, cmd/registry/patch/zip_test.go
=> update project properties with registry apply

cmd/registry/plugins/registry-lint-spectral/main.go
=> emit clear error when spectral is not installed

cmd/registry/cmd/compute/lint/lint-openapi-spectral.go, cmd/registry/cmd/compute/lint/lint-openapi-spectral_test.go
=> remove glob chars from spectral target filename

server/registry/actions_apis.go, server/registry/actions_apis_test.go, server/registry/actions_artifacts_test.go, server/registry/actions_deployment_revisions.go, server/registry/actions_deployment_revisions_test.go, server/registry/actions_deployments.go, server/registry/actions_deployments_test.go, server/registry/actions_projects.go, server/registry/actions_projects_test.go, server/registry/actions_spec_revisions.go, server/registry/actions_spec_revisions_test.go, server/registry/actions_specs.go, server/registry/actions_specs_test.go, server/registry/actions_versions.go, server/registry/actions_versions_test.go, server/registry/internal/storage/list.go
=> mega test coverage

.github/actions/registry-check/action.yaml
Disable flag was incorrectly using enable input
=> fix disable flag input

server/registry/actions_deployment_revisions_test.go
=> fix nightly build test

.github/actions/setup-registry/action.yml
=> default version to empty, not latest

cmd/registry/cmd/config/configurations/create.go
=> add --gcloud flag to registry create

.github/workflows/check.yml, .github/workflows/nightly-build.yml, .github/workflows/release.yml
=> Update setup-go action to v4

server/registry/internal/storage/client.go
Fixes #1192 
tested against DB reported in issue
=> rewrite migrateArtifactsToRevisions to avoid dups

server/registry/internal/storage/client.go
Updated for https://github.com/apigee/registry/issues/1192
=> ensure migrate artifacts is idempotent

cmd/registry/cmd/apply/apply.go, cmd/registry/cmd/auth/auth.go, cmd/registry/cmd/config/config.go, cmd/registry/cmd/config/configurations/activate.go, cmd/registry/cmd/config/configurations/configurations.go, cmd/registry/cmd/config/configurations/create.go, cmd/registry/cmd/config/configurations/delete.go, cmd/registry/cmd/config/configurations/describe.go, cmd/registry/cmd/config/configurations/list.go, cmd/registry/cmd/config/get.go, cmd/registry/cmd/config/list.go, cmd/registry/cmd/config/set.go
=> improve apply and config command help

containers/registry-server/Dockerfile
=> set builder to golang:1.20.4, remove toybox

containers/registry-server/Dockerfile
=> switch builder to golang:1.20-bullseye

cmd/registry-server/main.go, server/registry/server.go
=> db migrate on startup

server/registry/internal/storage/client.go
=> fix SpecRevisionTag foreign key migration query

cmd/registry/cmd/get/get.go
=> default --nested to yaml output

pkg/connection/grpctest/server.go
=> enable testing with no active configuration
