server/gorm/iterator.go
server/gorm/query.go

gorm cursors are object primary keys, which are currently the objects' resource names.
here we obscure this by base64-encoding cursors outside of the gorm package.

base64-encode cursors for gorm-based pagination

---

server/actions_apis.go
server/filters.go

This adds experimental code that adds a "labels" list to filtered objects when the "in labels" string is included in the CEL filter passd to a ListApis call. This allows label values to be used in filter strings, e.g.
```
registry list projects/$PROJECTID/apis --filter '$LABEL' in labels"
```
WARNING: this implementation is very slow so this feature should only be used on small API collections.

Experimental support for filtering APIs by label

---

tools/COMPILE-PROTOS.sh

This fixes a problem observed with recent versions of protoc (3.14.0
and possibly 3.13.X). Code in tools/COMPILE-PROTOS.sh "manually"
patches generated code to fix a problem in the automatic CLI generator.
This should be removed when that problem is fixed. We'll need
to file an issue on github.com/googleapis/gapic-generator-go.

Fix the patching in tools/COMPILE-PROTOS.sh for recent protoc versions

---

tools/COMPILE-PROTOS.sh

The COMPILE-PROTOS.sh setup script fails when dependencies are installed
to a Go bin directory that isn't accessible by the script (and the
programs it calls). This commit gives the script access to either the
custom or default Go bin directory in case it isn't already accessible.
The script also uses `sed` for string replacement in some files, but the
command behaves differently on the BSD and GNU versions of `sed`. When
the BSD version is used (e.g. on MacOS), then `sed -i -e ...` is
equivalent to `sed -i=-e ...`. When the GNU version is used, then `sed
-i -e ...` considers `-i` and `-e` as separate flags. This commit
updates the `sed` commands to have consistent behavior on BSD and GNU
versions of `sed`.

Increase portability of proto compilation script

---

cmd/registry/cmd/compute-lint.go
cmd/registry/core/lint-openapi.go

This uses the experimental linter in https://github.com/google/gnostic/tree/master/plugins/gnostic-linter to analyze OpenAPI descriptions against simple design rules, storing the results in the registry.

OpenAPI linter example

---

cmd/registry/cmd/compute-lint.go
cmd/registry/cmd/compute-lintstats.go
cmd/registry/core/lint-openapi-gnostic.go
cmd/registry/core/lint-openapi-spectral.go
cmd/registry/core/lint-openapi.go

This PR allows results from [Spectral](https://github.com/stoplightio/spectral) to be stored and displayed alongside other linting results. (Probably not ready for merging at least until the "lintstats" summarization is updated)

Add support for the Spectral linter and more generalized linting.

---

server/models/api.go
server/models/blob.go
server/models/label.go
server/models/project.go
server/models/property.go
server/models/spec.go
server/models/version.go

According to https://golang.org/pkg/reflect/#StructTag, struct tags are space-separated key-value pairs. For some reason, I thought these should be comma-separated, and recently noticed that these commas were preventing gorm from recognizing the primaryKey tags added to identify the primary keys in registry models.

remove commas from struct tags

---

Makefile
README.md
auth/GKE.sh
auth/README.md
cloudbuild.yaml
deployments/container/Dockerfile.envoy
deployments/gke/DEPLOY-TO-GKE.sh
deployments/gke/README.md
deployments/gke/deployment.yaml
deployments/gke/service-internal.yaml
deployments/gke/service.yaml

This change contains helper functionalities to deploy the registry server to GKE. Changes include:
- Generalize `make build` so database is configurable while building the container image.
- Add scripts to create and expose services on GKE.
- Add scripts to setup authentication of local clients.
- Add instructions in README

Add support to deploy on GKE

---

go.mod
go.sum
server/actions_status_test.go
server/server_test.go

This change establishes a pattern that can be used for testing all
functionality of the server package. It also restricts the scope of
tests to cover only the server RPC handler functionality.
Tests for the full server stack including gRPC and gapic client behavior
can be found in the `tests/` directory.

Create isolated test environment for server

---

server/models/artifact.go
server/models/spec.go
tests/crud/crud_test.go
tests/demo/demo_test.go

This also adds hash and content size to artifacts returned by the API.

Replace SHA-1 with SHA-256 hashing of specs and artifacts.

---

cmd/registry/cmd/compute-details.go
cmd/registry/cmd/compute-lint.go
cmd/registry/cmd/export-sheet.go
cmd/registry/cmd/get.go
cmd/registry/cmd/upload-bulk-openapi.go
cmd/registry/cmd/upload-bulk-protos.go
cmd/registry/core/print.go
demos/disco.sh
demos/protos.sh
server/actions_apis.go

With this, "registry get" for specs and artifacts will print the message body by default and, if the --contents flag is provided, the contents of the spec or artifact.

Fix a bug and an inconsistency in the "registry get" command

---

cmd/registry/cmd/upload-bulk-protos.go
cmd/registry/cmd/upload-spec.go
cmd/registry/core/types.go
tests/crud/crud_test.go
tests/demo/demo_test.go
tests/demo/walkthrough.sh

Following guidance from [MDN developer docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) and a formal syntax on [Wikipedia](https://en.wikipedia.org/wiki/Media_type), this removes the whitespace between `application/octet-stream;` and the `type` parameter. Note that this change only affects tools and not the core API, which currently does not require that `mime_type` values be valid Media Types.

Remove whitespace from artifact media type.

---

README.md
deployments/container/Dockerfile.envoy
deployments/envoy/GETENVOY.sh
deployments/envoy/envoy.yaml
tools/COMPILE-PROTOS.sh

This updates the Dockerfile and run scripts to allow the Registry server to be run in containers locally and in Kubernetes installations on both x86 and arm64 architectures. New README instructions document the process of building and running containers locally. Arm64 support required updating to Envoy 1.16 (which has published images for both x86 and arm64) and some small configuration changes related to the version change.

Add support for arm64 containers

---

server/actions_projects.go
server/actions_projects_test.go

* Fix bug in filtering large collections
* Add test for regression case
* Temporarily reintroduce incorrect page token responses
* Add TODOs to begin asserting correct page token behavior when fixed

Restore project pagination behavior

---

.gitignore
.vscode/launch.json

This change allows developers to debug tests using VSCode without
creating untracked files in their workspace. We could ignore the entire
directory if we want vscode users to have to generate their own
launch.json before debugging tests.

Add VSCode launch settings

---

server/actions_specs.go
server/actions_specs_test.go
server/actions_versions_test.go
server/datastore/deletions.go
server/gorm/deletions.go
server/storage/storage.go

This change doesn't include all the testing needed for the specs API. It just covers the main CRUD operations as we've covered them for projects/apis/versions. Some examples of behaviors that still need testing:
- Revisions
- Tagging
- UpdateSpec with allow_missing

Specs Testing + Handler Updates

---

demos/README.md
demos/openapi.sh
demos/protos.sh

Renaming "atlas" top "openapi" for consistency with the other format-specific demos.

rename the "atlas" demo to "openapi"

---

server/actions_apis.go
server/actions_projects.go
server/actions_projects_test.go
server/datastore/deletions.go
server/errors.go
server/gorm/deletions.go
server/models/api.go
server/models/project.go
server/names/project.go
server/storage/storage.go

This change is in preparation for incoming functional changes. The
purpose of adding a resource name type is to remove string processing
from our RPC handler implementations as the string manipulation
increases in complexity. Name types will be added to Api/Version/Spec in
a follow-up.
* Add type for project resource names, refactor APIs where applicable.
* Move project storage entity name into storage package.
* Refactor common project operations into helper functions.
* Check additional errors before returning
* Consistently use error helper functions.
* Remove redundant import names.

Refactor Projects API implementation

---

server/actions_apis.go
server/actions_apis_test.go
server/actions_versions.go
server/datastore/deletions.go
server/gorm/deletions.go
server/gorm/gorm_test.go
server/models/api.go
server/models/version.go
server/names/api.go
server/names/project.go
server/storage/storage.go

* Add type for API resource names, refactor interfaces where applicable.
* Move API storage entity name into storage package.
* Refactor common API operations into helper functions.
* Check additional errors before returning
* Consistently use error helper functions.
* Remove redundant import names.

Refactor API service

---

server/actions_specs.go
server/actions_versions.go
server/actions_versions_test.go
server/datastore/deletions.go
server/gorm/deletions.go
server/models/spec.go
server/models/version.go
server/names/api.go
server/names/version.go
server/storage/storage.go

* Add type for version resource names, refactor interfaces where applicable.
* Move version storage entity name into storage package.
* Refactor common version operations into helper functions.
* Check additional errors before returning
* Consistently use error helper functions.
* Remove redundant import names

Refactor Versions service

---

server/actions_apis.go
server/actions_apis_test.go

* Check for non-existent parent resources in List/Create methods
* Check basic/full API responses in Create/Get/Update methods
* Check that List only returns APIs from a specified parent project
* Check that List works across multiple collections

Expand testing for API methods

---

server/actions_apis.go
server/actions_artifacts.go
server/actions_projects.go
server/actions_specs.go
server/actions_versions.go

This fixes crashes that occurred when filter expressions did not evaluate to bool. Such expressions are now treated as invalid arguments.

fix crashes caused by brittle type cast in filter evaluation

---

server/actions_versions.go
server/actions_versions_test.go

* Check for non-existent parent resources in List/Create methods
* Check basic/full API responses in Create/Get/Update methods
* Check that List only returns versions from a specified parent API
* Check that List works across multiple collections

Expand testing for API Version methods

---

server/actions_apis.go
server/actions_apis_test.go
server/actions_projects.go
server/actions_projects_test.go
server/actions_versions.go
server/actions_versions_test.go
server/models/api.go
server/models/version.go

* Add check for resource body in Update methods
* Add notification on UpdateProject success
* Add seed data to ensure listing only returns expected resources
* Update model name methods to use names package
* Remove unnecessary manual population of IDs on storage reads

Fix forgotten Project/Api/Version behaviors

---

tools/COMPILE-PROTOS.sh

This command was previously. failing on MacOS leading to the insecure mode not working properly for different CLI tools.

Fix for sed command on MacOS

---

server/actions_apis_test.go
server/actions_projects_test.go
server/actions_spec_revisions.go
server/actions_spec_revisions_test.go
server/actions_specs.go
server/actions_specs_test.go
server/actions_status_test.go
server/actions_versions.go
server/actions_versions_test.go
server/datastore/deletions.go
server/gorm/deletions.go
server/gorm/iterator.go
server/models/spec.go
server/names/common.go
server/names/spec.go
server/names/spec_revision.go
server/names/version.go
server/storage/storage.go
tests/filters_test.go

* Add tests for method behaviors
* Move revision methods into separate file
* Order revisions by revision creation time
* Check for non-existent parent resources in List/Create methods
* Check basic/full API responses in Create/Get/Update methods
* Reject negative page sizes in List requests
* Return the correct page size and token on revision listing with sqlite
* Refactor existing methods to use common helper methods

Update API Spec and SpecRevision methods 

---

server/datastore/index.yaml

This fixes datastore test failures introduced in recent changes.

Update datastore indexes for use of RevisionCreateTime in spec queries.

---

server/dao/specs.go

It appears that we accidentally changed this to Timestamp in our recent refactor. Sorry to miss this in the review!

Set the filtering type of the spec mime_type field to String

---

server/actions_artifacts.go

With a recent change, calls to ListArtifacts stopped returning empty tokens when the end of a collection was reached. That will be addressd in an upcoming revision, but this temporarily fixes the problem by using the fact that the next page tokens provided by the storage backend don't change when the end of the collection has been reached. When the token that we're returning is the same as the token we received, we replace the token with an empty string.

temporary workaround to fix listing artifacts with the datastore backend

---

google/cloud/apigee/registry/v1/registry_service.proto
server/actions_artifacts.go
tests/crud/crud_test.go

This is the second set of changes related to #133 - these add a `/contents` accessor for Artifacts.

Get artifact contents

---

cmd/registry-graphql/graphql/specs.go
cmd/registry/cmd/bleve.go
cmd/registry/cmd/compute-complexity.go
cmd/registry/cmd/compute-descriptor.go
cmd/registry/cmd/compute-details.go
cmd/registry/cmd/compute-index.go
cmd/registry/cmd/compute-lint.go
cmd/registry/cmd/compute-lintstats.go
cmd/registry/cmd/compute-references.go
cmd/registry/cmd/compute-vocabulary.go
cmd/registry/cmd/upload-bulk-discovery.go
cmd/registry/core/get.go
cmd/registry/core/list.go
cmd/registry/core/specs.go
config/registry.yaml
go.mod
go.sum

This removes all dependencies on the `view` fields in Get and List methods. Contents of ApiSpecs and Artifacts are obtained using the new `/contents` accessors.

 Update registry tool and graphql demo to use "/contents" accessors.

---

google/cloud/apigee/registry/v1/registry_models.proto
google/cloud/apigee/registry/v1/registry_service.proto
server/actions_apis.go
server/actions_apis_test.go
server/actions_artifacts.go
server/actions_artifacts_test.go
server/actions_specs.go
server/actions_specs_test.go
server/actions_versions.go
server/actions_versions_test.go
server/models/api.go
server/models/artifact.go
server/models/spec.go
server/models/version.go
tests/crud/crud_test.go

This completely removes the view argument from Get and List methods. Now annotations are always returned and contents are never returned. The contents fields of both ApiSpecs and Artifacts are accessible using the GetApiSpecContents and GetArtifactContents methods, which also provide direct access to contents (with no protobuf message wrapping) through transcoded HTTP calls.

Remove support for view arguments to Get and List methods.

---

server/gorm/client.go
server/server.go

This moves a database configuration check to initialization, which will make it easier to recognize invalid configurations, particularly configuration to use SQLite when CGO is disabled.
Addresses #143

Validate database configuration on startup

---

.gitignore
tools/COMPILE-PROTOS.sh

- Another fix for `sed` on Mac
- .gitignore for IntelliJ

Minor build fixes

---

server/actions_spec_revisions.go
server/actions_spec_revisions_test.go
server/actions_specs.go
server/dao/apis.go
server/dao/artifacts.go
server/dao/dao.go
server/dao/projects.go
server/dao/spec_revisions.go
server/dao/specs.go
server/dao/versions.go
server/gorm/client.go
server/gorm/query.go
server/models/spec.go
server/storage/storage.go
tests/demo/demo_test.go

This change removes the "Currency" field from API spec models. Instead, the revision creation time is used to determine which spec revision is current. To achieve this, two major changes were necessary as prerequisites. Fixes #98.
1. Pagination using limit/offset instead of primary key.
Pagination using the primary key as a cursor only works if the query is ordered by key. We want to paginate spec revisions in order of their creation time and other resources in order by key, so a general purpose solution like limit/offset made the most sense. 
Note: Previously our iterators would read the entire table into memory and only iterate until a page is ready to return or the entire table has been read. Now the iterator can indicate it's "done" before the entire table has been read.
In the case …

Remove currency field from spec model

---

tools/COMPILE-PROTOS.sh

Recent changes to gapic-generator-go break a hacky patch that was added to support the graphql demo. I think we should remove that patch and possibly also the graphql demo, but since the change breaks CI, this quick change fixes the CI problems so we can keep our tests clean to avoid blocking other work.

quick (temporary) fix for changes in gapic-generator-go

---

cmd/registry/cmd/upload-bulk-openapi.go

This addresses most of #150 (but not the identifier length limit)

Filter/sanitize identifiers generated by "registry upload bulk openapi"

---

containers/BUILD.sh
containers/registry-tools/Dockerfile

This adds a Dockerfile for building a "registry-tools" container containing the `registry` and `apg` CLIs.

Add a Dockerfile for a container containing the registry CLI tools.

---

.gitignore
.vscode/launch.json

This allows custom launch configurations for each developer. Most people probably don't use custom launch configurations, but after I set one up I realized it affected the launch.json file and I didn't want to include my custom configurations with my changes.

Remove launch.json exception from .gitignore

---

cmd/registry/cmd/compute-lint.go

This is a small fix to return error in one of the cases for `compute-lint` command. 
I am not aware of any specific reason for why this was not done before, so assuming this is probably a code bug. I faced debugging issues while performing some tests. The command would return with no message and not display if there was an error or the it went through.

Bug Fix: return error from GetBytesSpecs in compute-lint.go

---

Makefile

Printing log and test pass information makes it difficult to find test
failures now that we have a large suite of tests. Verbosity is rarely
useful in running tests, but can still be achieved manually if desired.

Remove verbosity flag from Makefile test command

---

gapic/grpc_service_config.json

Errors that don't have a specified status code are considered "unknown"
and shouldn't be retried because we don't have reason to believe they
will succeed in future attempts. By retrying until timeout we lose the
information provided by the unknown error, and instead see the result of
a timeout.

Remove retry on unknown errors

---

cmd/registry/cmd/export-csv_test.go
cmd/registry/cmd/upload-csv_test.go
server/actions_apis.go
server/actions_apis_test.go
server/actions_artifacts.go
server/actions_artifacts_test.go
server/actions_projects.go
server/actions_projects_test.go
server/actions_spec_revisions_test.go
server/actions_specs.go
server/actions_specs_test.go
server/actions_versions.go
server/actions_versions_test.go

Fixes #70 by removing the feature entirely. If we don't want to remove the feature, much of this PR is still useful. I think it's a good idea for us to prefer using fixed IDs in our tests so we have the flexibility of removing generated IDs in the future.

Require custom IDs on resource creation

---

server/actions_apis_test.go
server/actions_projects_test.go
server/actions_specs_test.go
server/actions_versions_test.go
server/models/update_masks.go

The generated apg tool allows callers to set update_mask.paths with
fields, and defaults to an empty slice if none are provided. Every
request to update a resource from apg has a non-nil mask as a result.
This change adds a check for non-nil but empty field masks and behaves
the same as a nil mask in those cases, i.e. performs an implicit update.
Fixes #220

Use empty non-nil field masks as implicit updates

---

server/models/api.go
server/models/artifact.go
server/models/blob.go
server/models/project.go
server/models/spec.go
server/models/version.go

PostgreSQL doesn't support storage of nanosecond resolution timestamps
that can be generated in some environments. This change guarantees the
timestamps are created with a resolution that can be stored by our
supported databases.
Fixes #232

Generate microsecond resolution timestamps

---

cmd/registry/cmd/resolve/resolve.go
cmd/registry/cmd/resolve/resolve_test.go

Implementation of resolve command now calls the subcommands programmatically and not through `os.exec` calls.
Two limitations or follow up tasks:
* refactor WaitGroup implementation https://github.com/apigee/registry/issues/239
* Handle logging in a more structured way.
Both of the above tasks will change implementations of all the registry commands and hence would be best to handle them separately. In this change, the resolve command is calling the sub-tasks programmatically and doing it in a serially. We can switch back to `taskQueues` once the `WaitGroup`  refactor is done.

Restructure resolve command

---

cmd/registry/main.go

Addresses some concerns from #243. Each child command will have a unique ID associated with its logs, allowing them to be inspected together as a group while ignoring interleaved logs from concurrently executing commands. This allows easy inspection of logs when commands are executed concurrently.
As our logging continues to improve we can relocate this unique ID into the command's context where it can be reused by the server logs for easier system-wide analysis. We will need to migrate away from using a global default logger before this can be implemented.
This change does not provide any information about the relationship between parent/child commands. For example, `registry resolve` may execute several children `registry` commands, and each will have a unique ID, but logs in the …

Add unique per-process ID to registry command logs

---

cmd/registry/cmd/resolve/resolve.go
cmd/registry/controller/local-tasks.go

This PR includes the following changes:
1) Setting the output of child commands to StdOut and StdErr so that the logs generated by the child commands are all visible.
2) `local-tasks.go`: Each individual go routine will log the completion of a command execution by logging the status, action and taskID (will be tied to child command's uid in the future). This information should be enough for now to generate basic summary dashboards like: total num actions, num failures, % success, etc

Include completion information in controller's tasks

---

cmd/registry/cmd/upload/styleguide.go
cmd/registry/cmd/upload/upload.go
google/cloud/apigee/registry/applications/v1alpha1/registry_api_style_guide.proto
google/cloud/apigee/registry/applications/v1alpha1/registry_styleguide.proto
tools/COMPILE-PROTOS.sh

API Style Guides are a declarative solution to define the static analysis of API specs within a project. An API Style Guide is described by the proto that is defined in this pull request. It contains a list of guidelines along with linters that enforce those guidelines.
This pull request creates the API Style Guide proto, and also implements a CLI to upload YAML files that describe an API Style Guide to the registry, where it is attached as an artifact to a provided project ID.
1. Create a file called `styleguide.yaml` in your home directory, with the following contents:
```yaml
name: openapistyleguide
mime_types:
- application/x.openapi+gzip;version=2
guidelines:
- name: refproperties
display_name: Govern Ref Properties
description: This guideline governs properties for ref fields on …
```

Implement API Style Guide Proto definition, and ability to upload API Style Guides in YAML Format

---

.github/workflows/go.yml

Temporary change to keep CI working while we make changes needed for 1.16 and 1.17

Pin the Go version used for CI to 1.15.*

---

cmd/registry/cmd/upload/styleguide.go
google/cloud/apigee/registry/applications/v1alpha1/registry_styleguide.proto

This pull request addresses comments left post-merge on #283. It addresses all but one, which is to break out mime types into a constant field. Such a change is broad and can be part of a refactor where it is also done in other places in the registry.

Improve documentation on Style Guide, and do code cleanup for uploading functionality

---

cmd/registry/cmd/upload/styleguide_test.go
cmd/registry/cmd/upload/testdata/styleguide.yaml

These changes test the changes introduced in `cmd/registry/cmd/upload/styleguide.go` in #283.
- `cd` into `registry/cmd/registry/cmd/upload`
- Run `go test -count 1 -run TestStyleGuideUpload`
- Ensure that the test passes

Unit Tests for uploading Style Guides

---

cmd/registry/cmd/compute/lintstats.go
cmd/registry/cmd/export/csv.go
cmd/registry/cmd/export/csv_test.go
cmd/registry/cmd/upload/csv_test.go
cmd/registry/core/get.go
cmd/registry/core/list.go
cmd/registry/core/specs.go
demos/disco.sh
demos/openapi.sh
demos/protos.sh
google/cloud/apigee/registry/v1/registry_service.proto
openapi.yaml
server/actions_artifacts.go
server/actions_specs.go
server/actions_specs_test.go
tests/crud/crud_test.go
tests/demo/walkthrough.sh

This is a small breaking change (sorry about that!) which makes the API more consistent with [AIP-121](https://google.aip.dev/121).
Because "contents" is a field of API specs and artifacts, we decided that it's better to not treat it as a full AIP-121 resource, which has complicating implications for some intended hosting platforms and related tools.

Replace /contents singleton accessors with custom :getContents methods.

---

cmd/registry/cmd/resolve/testdata/manifest.yaml
cmd/registry/cmd/resolve/testdata/manifest_receipt.yaml
cmd/registry/cmd/upload/manifest.go
cmd/registry/cmd/upload/manifest_test.go
cmd/registry/cmd/upload/styleguide.go
cmd/registry/cmd/upload/styleguide_test.go
cmd/registry/cmd/upload/testdata/manifest.yaml
cmd/registry/cmd/upload/testdata/styleguide.yaml
cmd/registry/controller/controller_test.go
cmd/registry/controller/testdata/manifest.yaml
cmd/registry/controller/testdata/manifest_e2e.yaml
cmd/registry/controller/testdata/manifest_test.yaml
google/cloud/apigee/registry/applications/v1alpha1/registry_manifest.proto
google/cloud/apigee/registry/applications/v1alpha1/registry_styleguide.proto
tests/controller/testdata/manifest.yaml

In the registry, the convention that we use is that `name` fields are typically given to resource names. A resource name is one that matches: `projects/{project_id}/locations/{location}/apis/{api}/versions/{version}/specs/{spec}/artifacts/{artifact}`.
However, in the case of manifests and style guides, the `name` field is actually being used as an identifier rather than an actual resource name. Thus, we should correct our terminology and call them what they really are, `id`s.
Existing unit tests should pass. There is no extra manual test that needs to be done, since all of the tests pertaining to this are automated.

Refactor 'name' field to ID on style guide and manifest proto definition

---

cmd/registry-server/main.go
server/actions_apis.go
server/actions_artifacts.go
server/actions_projects.go
server/actions_spec_revisions.go
server/actions_specs.go
server/actions_versions.go
server/internal/storage/gorm/client.go
server/internal/storage/gorm/query.go
server/notifications.go
server/server.go

This PR addresses most features of #318 and #319. 
Notably this does not make the log output format configurable which means Cloud Logging may not even recognize that the logs are structured. It also doesn't include any logging for database interactions in the server. These features are important to add before closing those issues, but this PR stands on its own without them.

Structured logging for the registry server

---

containers/registry-server/Dockerfile
containers/registry-tools/Dockerfile

Removes "make protos" steps from the dockerfiles for registry-server and registry-tools - protos are now precompiled and in the repo and these steps fail for our current build configuration.

Fix dockerfiles for build process changes.

---

cmd/registry/cmd/upload/styleguide.go
cmd/registry/core/print.go

Encountered this issue while testing some controller use-cases.  Some of the artifact types were not showing the deserialized contents, for example, `registry get projects/demo/locations/global/artifacts/test-manifest --contents` command. 
Solution: They were missing the deserialization logic in `PrintArtifactContents`.

Fix 'registry get ... --contents' for certain artifact types

---

.github/workflows/docker-publish.yml
cloudbuild.yaml

This updates the product of the docker-publish GitHub action to match the executable name and the container definition in the [containers](https://github.com/apigee/registry/tree/main/containers) directory.
I guess this build is using the Dockerfile at the root of the repo. That's a link to this [Dockerfile](https://github.com/apigee/registry/blob/main/containers/registry-server/Dockerfile) in [containers/registry-server](https://github.com/apigee/registry/tree/main/containers). If possible, it would be good to have a second build that builds the [registry-tools](https://github.com/apigee/registry/blob/main/containers/registry-tools/Dockerfile) container. @giteshk could that be done with this action or would we need to set up another one? 
@shrutiparabgoogle if we built the …

Rename docker image target to "registry-server".

---

go.mod
go.sum

This addresses the following problem installing `registry-server`:
```
$ go install github.com/apigee/registry/cmd/registry-server@latest
go install: github.com/apigee/registry/cmd/registry-server@latest (in github.com/apigee/registry@v0.3.8):
The go.mod file for the module providing named packages contains one or
more replace directives. It must not contain directives that would cause
it to be interpreted differently than if it were the main module.
```

Run go mod tidy and remove replace directive.

---

cmd/registry/plugins/registry-lint-api-linter/main.go
cmd/registry/plugins/registry-lint-openapi-sample/README.md
cmd/registry/plugins/registry-lint-openapi-sample/main.go
cmd/registry/plugins/registry-lint-openapi-sample/main_test.go

The following pull request creates a sample OpenAPI linter which serves as a proof-of-concept for custom linter creation in the API Registry. It lints two rules:
- `description-less-than-1000-chars`: Ensures that description fields in the OpenAPI spec are less than 1000 characters.
- `description-contains-no-tags`: Ensures that description fields in the OpenAPI spec contain no tags (such as HTML tags).
- Have registry running on `localhost:8080`.
- Place [the following OpenAPI Sample spec](https://gist.github.com/muhammadharis/13f1681ad65bf6a59366f3068748c0d8) into ~/petstore.yaml 
- Run `LOCAL.sh`
- Ensure that the following style guide is located under `~/styleguide.yaml`:
```yaml
id: openapistyleguide
mime_types:
- application/x.openapi+gzip;version=2
- …
```

Implement a sample linter for OpenAPI that enforces rules on descriptions

---

Makefile
README.md
deployments/envoy/envoy-auth.yaml
deployments/envoy/envoy-noauth.yaml
deployments/envoy/envoy.yaml
tests/demo/walkthrough.sh

`make build` was failing because the `cloubuild.yaml` was updated to use the default `PROJECT_ID` in this [PR](https://github.com/apigee/registry/pull/369/files#diff-0b4a5fc26445836e6672c426692297004cfaba21997343b63e6f58b946bd2a5c). 
Updating the README file Protoc version is required to be `3.18.1` as part of this [PR](https://github.com/apigee/registry/commit/a55ab928c4da8d8d8123887177c5ed16f3a471d0#diff-bfb65189e4c34ea327b657f569d9ca1a2c22f6bd16878aea2aa7a3dd3b9cb164)
Adding `google.cloud.apigeeregistry.v1.Admin` service in the `envoy.yaml` file to support http transcoding for the admin service.
Adding `locations/global` in the path for the demo script at `tests/demo/walkthrough.sh`.

Fixing some issues found during a recent data plane deployment

---

.github/workflows/composite/build-push/action.yml
containers/registry-linter/Dockerfile

I don't see any runs for this action in our [history](https://github.com/apigee/registry/actions) but it looks like it will fail if it ever runs because these addresses point to an available domain name gchr.io, not the ghcr.io domain used by GitHub's container registry.

Fix GitHub container registry addresses

---

server/registry/actions_artifacts.go
server/registry/actions_artifacts_test.go

This fixes a problem creating artifacts discovered by @Krpate - we were failing to create artifacts when their parent type was "ApiDeployment". With the (small) fix, I've added artifact creation tests for all parent types (we had tests for project parents; the new tests cover APIs, versions, deployments, and specs).

Fix artifact creation problem, test artifact creation for all parent types

---

auth/CLOUDRUN.sh
auth/ENVOY.sh
auth/GKE.sh
auth/LOCAL.sh
cmd/apg/admin_service.go
tools/GENERATE-APG.sh

This eliminates the use of APG_ADMIN_* variables to configure the Admin service client, replacing them with APG_REGISTRY_* so that both services are configured with the same variables.

Patch apg to make the Admin client use the Registry client configuration

---

gapic/grpc_service_config.json
gapic/registry_client.go

Update GAPIC configuration to increase timeouts to 20s and retry two additional gRPC response codes (Abort, Cancelled).
In testing with hosted deployments, "Abort" codes are returned when prerequisite operations have failed to complete. Retrying these aborted calls generally succeeds. "Cancelled" codes are returned when calls are rate-limited. Again, retrying these callsl generally succeeds (with appropriate backoffs, which are built into the GAPICs).
The timeout increase works around issues where proxies preemptively expire cancel requests with timeouts that are considered too short.

Update GAPIC config: 20s timeouts, additional retries

---

tests/benchmark/apis_test.go

After discussing some ideas for benchmarking the performance of our API
methods I wanted to see how Go's benchmark package would work. This
change includes some simple examples for the API resource's CRUD methods.
These benchmarks don't examine the response for correctness (aside from
an error check) because it might significantly affect the performance.
The benchmarks don't need to (and shouldn't) test the correctness of
responses because other test suites already check this.
The tests can executed using `go test -bench=. ./tests/benchmark/...` or
compiled using `go test -c ./tests/benchmark/...` and executed using the
resulting binary with the `test.bench=.` flag.
Example benchmark output:
```
goos: darwin
goarch: amd64
pkg: github.com/apigee/registry/tests/benchmark
cpu: Intel(R) …
```

Add CRUD benchmarks for API methods

---

cmd/registry/cmd/compute/conformance.go

guidelineIDs were not getting populated in conformance reports

Fix for conformance.go

---

.golangci.yaml
cmd/registry/cmd/compute/conformance_test.go

I noticed some linter warnings appeared in VS Code after some recent changes. It looks like when we switched to golangci-lint I forgot to enable `gofmt` as one of the linters it runs, even though that's the only linter we ran previously.
Note: Anyone using the Go extension for VS Code has some set of automatic syntax validation and linting enabled by default.

Add gofmt to golangci-lint config

---

server/registry/names/project.go

We noticed that CreateAPI calls were accepting arbitrary location values, where all others required that the location be "global". In the future, we may expand our support to allow arbitrary locations, but for consistency, this corrects the regex used to parse located projects so that the location value must be "global".
Verified manually with:
```
apg registry create-api --parent projects/openapi/locations/invalid --api_id test
```

Require "global" as the location when parsing project names with location

---

google/cloud/apigeeregistry/v1/registry_models.proto

Came across this error when I was trying to generate typescript client from the proto definitions

Fixed the type for ApiDeployment

---

gapic/grpc_service_config.json
gapic/registry_client.go

This causes the Go GAPICs to retry calls that fail due to DeadlineExceeded errors. We should keep an eye on this to watch for situations where operations consistently fail due to needing too much time, but in current practice we're seeing that deadline failures are generally occurring due to transient situations that are resolvable with retries.

Update GAPIC gRPC service configuration to retry DeadlineExceeded errors

---

server/registry/actions_artifacts.go
server/registry/actions_artifacts_test.go

I noticed we didn't have tests for this RPC method, so I copied the cases from `TestGetApiSpecContents` and adjusted them for the artifact resource type. One of the cases failed, which led me to find that `GetArtifactContents` wasn't decompressing gzipped artifact contents as it [claims to support](https://github.com/apigee/registry/blob/61c5bc7df3a3ddbdb9587ae184b5d26a2931b39e/google/cloud/apigeeregistry/v1/registry_service.proto#L328). This PR adds that functionality and some tests for the method.

Add tests and decompression support for GetArtifactContents 

---

server/registry/internal/storage/get.go

Unexpectedly, the Last method in GORM's query builder doesn't select the
last row in the query result. Instead, it adds an additional ordering
parameter to order by descending primary key and takes the first row in
the overall query result. With our queries, it has no effect on the
ordering and results in the first row, i.e. the row with the oldest
revision_create_time, being selected.
This fix just reverses the ordering in our query and selects the first
row, so we always pick the most recent revision_create_time.

Update gorm query to fix ordering bug

---

cmd/registry/cmd/resolve/resolve.go
cmd/registry/core/tasks.go

This is required to reduce the noise in the controller's execution logs.
Currently, if a controller generates 10 actions and even one of those actions fails, we report that error as failure and the `resolve` command returns with exit code 1. This is not a failure of the controller but a task failure. We don't want this to be reported as a controller failure.
Solution: 
Controller will report errors in the following ways:
1. Log `Fatal` errors if the controller is:
- not able to connect to the registry.
- not able to fetch the manifest.
- not able to read the state of the registry.
and return with non-zero exit code.
2. Report `Warn` if there is error in any of the tasks which executed the actions. The underlying tool which executes the task is already logging error messages for failure. …

Report controller task errors as warnings and not Fatal

---

.github/workflows/go.yml

Upgrade golangci-lint to v1.45 to support Go 1.18

---

containers/registry-tools/Dockerfile

When writing simple controllers which may be querying information from an external URL it would be easier to just use `curl` instead of having to build a new container on top of registry-tools.
Most of the information returned by registry-tools commands is in JSON format. 'jq' provides an easy way to query the information and use it to build shell scripts

Add curl, jq to registry-tools

---

go.mod

I'm starting to think `go mod tidy` should be running automatically at some point. It shouldn't be possible to have dependencies listed incorrectly in this file.
* Correctly annotate indirect dependency `golang.org/x/net`
* Regroup direct and indirect dependencies into separate `require` statements

Update go.mod dependencies

---

README.md
tests/demo/walkthrough.sh

This removes a README reference to Cloud Run configuration in the Makefile (deprecated, to be moved to registry-experimental), updates the README to refer to tools/PROTOC_VERSION.sh for the currently-used protoc version, and fixes a bug in the tests/demo/walkthrough.sh script (see also #556).

Fix a few small problems in the top-level README.md

---

.gitattributes
README.md
auth/README.md
cmd/registry/README.md
tools/registry-decode-spec/main.go

Some of these changes were in #571, now on hold.

Fix lingering references to the apg tool

---

demos/setup-project.sh

This recently-added demo script uses `registry rpc admin` subcommands to delete a project (if it exists) and create a new one.
Errors in the delete command will occur if the project doesn't already exist, so to reduce confusion we suppress those by redirecting stdout/stderr to /dev/null. Errors other than NOT_FOUND will likely be reported by the subsequent create command, which gets a `--json` flag to make its output more readable.

Tweak setup-project.sh to minimize confusion.

---

cmd/registry/cmd/compute/complexity.go
cmd/registry/cmd/compute/compute.go
cmd/registry/cmd/compute/conformance.go
cmd/registry/cmd/compute/conformance_test.go
cmd/registry/cmd/compute/lint.go
cmd/registry/cmd/compute/lintstats.go
cmd/registry/cmd/compute/references.go
cmd/registry/cmd/compute/score.go
cmd/registry/cmd/compute/scorecard.go
cmd/registry/cmd/compute/vocabulary.go
cmd/registry/conformance/conformance-task.go
cmd/registry/scoring/score.go
cmd/registry/scoring/score_test.go
cmd/registry/scoring/scorecard.go
cmd/registry/scoring/scorecard_test.go

I started this PR with adding `dry-run` support for score commands. 
However, it would be better to add that support across compute commands since each compute sub-command is uploading some artifact to the registry, users should have the option of not uploading the artifact.

Dry run support in compute command

---

cmd/registry-server/main.go
cmd/registry/cmd/compute/conformance_test.go
cmd/registry/cmd/resolve/resolve_test.go
cmd/registry/cmd/upload/artifact.go
cmd/registry/cmd/upload/bulk/openapi.go
cmd/registry/cmd/upload/bulk/protos.go
cmd/registry/cmd/upload/csv.go
cmd/registry/cmd/upload/csv_test.go
cmd/registry/cmd/upload/manifest.go
cmd/registry/cmd/upload/spec.go
cmd/registry/cmd/upload/styleguide.go
cmd/registry/conformance/conformance-task.go
cmd/registry/core/gzip.go
cmd/registry/core/lint-openapi-gnostic.go
cmd/registry/core/lint-openapi-spectral.go
cmd/registry/core/lint-openapi.go
cmd/registry/core/lint-proto.go
cmd/registry/diff/differ_test.go
cmd/registry/googleauth/client.go
cmd/registry/patch/apply.go
cmd/registry/patch/spec.go
cmd/registry/plugins/linter/lint_framework.go
cmd/registry/plugins/registry-lint-api-linter/main_test.go
cmd/registry/plugins/registry-lint-openapi-sample/main.go
cmd/registry/plugins/registry-lint-openapi-sample/main_test.go
cmd/registry/plugins/registry-lint-spectral/main.go
cmd/registry/plugins/registry-lint-spectral/main_test.go
server/registry/internal/storage/models/gzip.go
tests/crud/crud_test.go
tests/demo/demo_test.go

Following [this discussion](https://github.com/apigee/registry/pull/586#discussion_r884027359) and [this reference](https://go.dev/doc/go1.16#ioutil), this replaces all usage of functions from `ioutil` with recommended alternatives.

Replace ioutil functions with recommended alternatives

---

cmd/registry/patch/artifact.go

Populate `Id` and `Kind` fields in artifact contents while reading from serialized yamls
Fixes https://github.com/apigee/registry/issues/594

Fix for missing Id in artifacts through `apply` command

---

server/registry/actions_specs.go
server/registry/actions_specs_test.go
server/registry/internal/storage/models/spec.go

Fixes #626 by applying updates to spec contents only _after_ updating every other field on the model. This guarantees the `mime_type` is up-to-date when we check whether to decompress the contents before recomputing `size_bytes` and `hash`. 
See https://github.com/apigee/registry/issues/626#issuecomment-1165796491 for a full description of the bug and solution.

Fix gzip validation for UpdateApiSpec

---

pkg/wipeout/wipeout_test.go

This allows the wipeout test to run when there is no external server running or configured.

Update wipeout test to use an auto-started server when necessary.

---

cmd/registry/cmd/root.go
cmd/registry/cmd/rpc/generated/admin_service.go
cmd/registry/cmd/rpc/generated/provisioning_service.go
cmd/registry/cmd/rpc/generated/registry_service.go
pkg/connection/README.md
pkg/connection/client.go
pkg/connection/grpctest/server.go
pkg/connection/settings.go
pkg/connection/settings_test.go
pkg/wipeout/wipeout_test.go
tools/GENERATE-CLI.sh

Enables config file usage and flags as follows:
Flags enabled for registry CLI:
```
-c, --config string             Name of a settings profile or path to config file
--registry.address string   the server and port of the registry api (eg. localhost:8080)
--registry.insecure         set to true if client must connect via http (not https)
--registry.token string     the token to use for authorization to registry
```
Notes:
* This is 100% backward compatible
* `go test` will use env vars, not flags
* Settings are honored in prioritized order from: 1. flags, 2. env vars, 3. config file
* Config files are assumed to be stored in $HOME/.config/registry
* However, `--config` flag can specify an explicit path to a settings file directly
Config file management will be handled in #649 
Fixes #647

Enable config file usage and flags

---

server/registry/actions_artifacts_test.go

This fixes a couple of small coverage gaps in `actions_artifacts_test.go`

Explicitly test listing of artifacts for all parent types.

---

server/registry/actions_migrate_database.go
server/registry/actions_migrate_database_test.go

This increases test coverage of `actions_migrate_database.go` from zero to 73% (all but a few returns from error conditions).

Add simple tests for the MigrateDatabase admin rpc.

---

.github/workflows/go.yml

This defers startup of the standalone `registry-server` to ensure that all of the `make test` tests can run with the built-in test server which is run from  [`TestMain()` in `pkg/connection/grptest`](https://github.com/apigee/registry/blob/a14cd98c777af469363cae18b8efff2a43169a64/pkg/connection/grpctest/server.go#L62).
A few test phases also get some minor renaming for clarity.

Registry tests: Reorganize CI testing to move standalone server tests later.

---

.github/workflows/go.yml

- replace `make test` with `go test ./...`
- use built-in server for coverage testing

Minor cleanup to CI tests

---

pkg/config/configuration_test.go
pkg/connection/client_test.go

ignore ext `APG_REGISTRY` vars in config tests

---

cmd/registry/cmd/annotate/annotate.go
cmd/registry/cmd/compute/complexity.go
cmd/registry/cmd/compute/conformance.go
cmd/registry/cmd/compute/lint.go
cmd/registry/cmd/compute/lintstats.go
cmd/registry/cmd/compute/references.go
cmd/registry/cmd/compute/vocabulary.go
cmd/registry/cmd/count/revisions.go
cmd/registry/cmd/count/versions.go
cmd/registry/cmd/delete/delete.go
cmd/registry/cmd/diff/diff.go
cmd/registry/cmd/export/csv.go
cmd/registry/cmd/export/sheet.go
cmd/registry/cmd/export/yaml.go
cmd/registry/cmd/get/get.go
cmd/registry/cmd/index/index.go
cmd/registry/cmd/label/label.go
cmd/registry/cmd/list/list.go
cmd/registry/cmd/resolve/resolve.go
cmd/registry/cmd/util/util.go
cmd/registry/cmd/util/util_test.go
cmd/registry/cmd/vocabulary/vocabulary.go
pkg/config/config.go
pkg/config/configuration.go
pkg/config/configuration_test.go
pkg/connection/config.go
pkg/connection/config_test.go

This isn't as elegant as I'd like, but I didn't see a good integration point that could fix it as a cross-cutting concern. Reworking the naming package to require configuration didn't seem reasonable. One potential alternative to this rather brute-force approach would be to rework the configured clients to include naming lookups... however, right now they are direct pointers to the generated clients... so we'd have to wrap them in our own client structs instead and change the references. I can investigate that (or other ideas) if the solution in this PR isn't desireable.
Fixes #677

add project, location config and allow short names

---

cmd/registry/cmd/config/configurations/configurations_test.go
cmd/registry/cmd/config/configurations/create.go

Clones current active configuration using any flag overrides when creating a new configuration.
Fixes #692

 clone active w/ flags on config create

---

log/interceptor/interceptor.go

As mentioned [here](https://github.com/apigee/registry/pull/700#discussion_r959011449), this expands error printing to report all possible gRPC error codes.

Update logging interceptor to print all gRPC status codes.

---

server/registry/actions_apis.go
server/registry/actions_artifacts.go
server/registry/actions_deployments.go
server/registry/actions_projects.go
server/registry/actions_specs.go
server/registry/actions_versions.go
server/registry/internal/storage/lock.go

This is an alternate (and somewhat brute-force) approach to addressing race conditions mentioned in #448 and partially addressed in #715. It locks entire tables during update operations -- the full-table lock is needed because the update action first checks to see if a row exists, and if no row is present, there's no row to lock to prevent other processes or threads from trying to create it. The table locks are not supported by SQLite (it errors, so the locks are excluded for SQLite), and they are redundant because SQLite already locks tables during transactions.
Locks are automatically released when transactions end.
https://stackoverflow.com/a/72680220
https://www.postgresql.org/docs/current/explicit-locking.html#LOCKING-TABLES

Lock the table of affected entities during update operations.

---

cmd/registry/cmd/annotate/annotate.go
cmd/registry/cmd/compute/complexity.go
cmd/registry/cmd/compute/conformance.go
cmd/registry/cmd/compute/lint.go
cmd/registry/cmd/compute/lintstats.go
cmd/registry/cmd/compute/references.go
cmd/registry/cmd/compute/vocabulary.go
cmd/registry/cmd/count/revisions.go
cmd/registry/cmd/count/versions.go
cmd/registry/cmd/delete/delete.go
cmd/registry/cmd/diff/diff.go
cmd/registry/cmd/export/sheet.go
cmd/registry/cmd/export/yaml.go
cmd/registry/cmd/get/get.go
cmd/registry/cmd/label/label.go
cmd/registry/cmd/list/list.go
cmd/registry/cmd/resolve/resolve.go
pkg/config/config.go

Example:
```
$ registry get something
WARN: deprecated env: APG_REGISTRY_ADDRESS="localhost:8080"
WARN: deprecated env: APG_REGISTRY_INSECURE="1"
DEBUG[0000] Unsupported entity [projects/theganyo-1/locations/global/something] uid=6965bb68
```
Note: Also fixes commands where we were unnecessarily loading config twice causing duplicate warnings.
Fixes #702

deprecation warning for client env var use

---

server/registry/internal/storage/client.go

This applies fairly tight restrictions to database connection usage. When all connections are in use, the server blocks until one becomes available. This can cause operations to take longer when concurrency is high, but by not consuming all available connections, this keeps the database available for other clients. As noted in the comments, I think we may want to make this configurable.

Set limits on the number and lifetime of connections.

---

server/registry/internal/storage/client.go

Missed in https://github.com/apigee/registry/pull/627 in reference to https://github.com/apigee/registry/issues/622.

use prepared statements in postgres

---

cmd/registry/cmd/rpc/generated/list-api-deployments.go
cmd/registry/cmd/rpc/generated/list-api-specs.go
cmd/registry/cmd/rpc/generated/list-api-versions.go
cmd/registry/cmd/rpc/generated/list-apis.go
cmd/registry/cmd/rpc/generated/list-artifacts.go
cmd/registry/cmd/rpc/generated/list-projects.go
gapic/admin_client.go
gapic/admin_client_example_test.go
gapic/doc.go
gapic/provisioning_client.go
gapic/provisioning_client_example_test.go
gapic/registry_client.go
gapic/registry_client_example_test.go

This will hopefully reduce noise/churn for anyone regenerating the Go GAPIC.
Generated by running `make all` and committing the changed source files.

Update generated client code with the latest gapic-generator-go

---

cmd/registry/cmd/get/get.go
cmd/registry/core/print.go

Prior to this change, the `registry get` command did not offer a way to directly access the raw contents of artifacts - it printed known types as JSON and for unknown types, it printed a nearly-useless text dump of bytes for unknown types. This adds two new flags to `registry get`:
- `--raw`, which causes the command to write the raw bytes of the artifact to standard output.
- `--print`, which causes the command to print a formatted version of known artifact types to standard output. For unknown types, an error is printed with a message to use `--raw` to access the raw bytes.
To avoid disruption, the `--contents` flag is kept and associated with `--print` but a deprecation warning is printed when it is used.
Likely followup issues:
1. modify `--print` for specs to disallow printing of zip …

Registry tool: Deprecate `--contents` flag on `registry get`, replace it with `--print` and `--raw`

---

cmd/registry/cmd/upload/bulk/protos.go
cmd/registry/core/zip.go
cmd/registry/plugins/registry-lint-api-linter/main.go
cmd/registry/plugins/registry-lint-api-linter/main_test.go
server/registry/internal/storage/client.go

This makes proto-based API specs fully self-contained. Before uploading protos, the uploader uses `protoc` to compile them and collect a list of referenced files, repeating until all transitive inclusions are listed, and then all of these files are included in the zip archive, making the uploaded spec "fully resolved". The resulting zip archives can be unzipped in a fresh directory and compiled with `protoc` for use in any other desired applications.
A new `--protoc-root` option allows the bulk uploader to upload individual protobuf specs. When `--protoc-root` is used to specify the proto compilation root, the `PATH` argument can point to a subdirectory of that root that includes a directory containing a single API. For example, the registry API can be individually uploaded with the …

Upload dependencies of protos in uploaded APIs.

---

pkg/wipeout/tasks.go
pkg/wipeout/wipeout.go
pkg/wipeout/wipeout_test.go

Removes much of the wipeout logic from the client and allows server to do the work. This is more efficient and leaves less chance of partial failure. 
In addition, it fixes #755 - the test was hanging on a channel read.

move most of wipeout to the server

---

server/registry/internal/storage/client.go
server/registry/internal/storage/list.go

Optimization: If result size is less than the requested limit, it's not necessary to query the next page for more results.

optimize paging

---

cmd/registry/cmd/apply/apply.go
pkg/connection/config.go

This makes `--parent` optional for `registry apply` by using the configured `registry.project` when it is nonempty.
Manually verified... I looked into writing tests for this and didn't see a good way to set the registry configuration in an isolated way. Reviewers, WDYT? I'm thinking maybe the tests should save the configuration, modify it as needed, and put it back afterwards, but that seems risky and messy. Since we're not actually running the registry tool in tests, could there be a better way to do this by writing the configuration data structures directly?

Enhance "registry apply" to infer --parent from registry configuration.

---

.github/workflows/go.yml

Something started suddenly going wrong with our Postgres tests:
```
Run go test ./server/registry -postgresql
ERROR[0000] Failed database operation. duration=[6](https://github.com/apigee/registry/actions/runs/3284143678/jobs/5410886922#step:10:7)44.309µs error=pq: permission denied for schema public query=CREATE TABLE "projects" ("key" text,"project_id" text,"display_name" text,"description" text,"create_time" timestamptz,"update_time" timestamptz,PRIMARY KEY ("key"))
INFO[0000] Unhandled *pq.Error pq: permission denied for schema public code=42501 name=insufficient_privilege
--- FAIL: TestCreateApi (0.05s)
--- FAIL: TestCreateApi/fully_populated_resource (0.05s)
actions_apis_test.go:[8](https://github.com/apigee/registry/actions/runs/3284143678/jobs/5410886922#step:10:9)1: Setup: failed …
```

Address postgres failures in CI

---

server/registry/server_test.go

While debugging #786 I saw a lot of messages in the logs saying that we were falling back to sqlite after the postgres setup failed.
What do we lose by removing that fallback? Here's a change that does so. The postgres test setup seems to be tied to the `-postgres` flag, so I think it would be reasonable to fail when we can't connect to postgres.

In testing, don't fallback to sqlite when postgres is specified and unavailable.

---

.github/workflows/docker-publish.yml
.github/workflows/go.yml
.github/workflows/release.yml

Feeling a bit burned by the surprise failures that led to #786, I'd like to also pin the ubuntu image used in testing to an explicit version. Any concerns?

Replace ubuntu-latest in actions with ubuntu-22.04

---

cmd/registry/cmd/upload/bulk/openapi_test.go
cmd/registry/cmd/upload/bulk/protos_test.go

Discussed in #785, these tests are adding too much noise to CI.

Temporarily disable flaky bulk upload tests.

---

cmd/registry/cmd/apply/apply_test.go
pkg/connection/config.go

This includes modifications to the config package that allow the registry.project to be forced to particular values during testing.
I'm not attached to the implementation, this is just one way to pursue a goal of testing the registry tool under different configurations without modifying files in possibly-surprising ways.

Allow overriding the registry tool configuration in tests.

---

cmd/registry/cmd/compute/complexity.go
cmd/registry/cmd/compute/complexity_test.go

I noticed that `registry compute complexity` wasn't working for large specs, even if they were stored gzipped, because it was downloading them without allowing for gzip encoding. This change uses a standard utility from the `registry` tool's `core` package and now supports both gzipped and plain specs. I've also added one test for `compute complexity` and think we could easily add more if needed.

Enhance registry compute complexity to support gzipped specs, add test.

---

server/registry/actions_apis_test.go
server/registry/actions_artifacts.go
server/registry/actions_artifacts_test.go
server/registry/actions_deployments_test.go
server/registry/actions_projects_test.go
server/registry/actions_specs_test.go
server/registry/actions_versions_test.go

This fixes #792 and verifies with tests. Projects, APIs, and versions were already setting timestamps correctly, and artifacts weren't (and are fixed). Although specs and deployments weren't mentioned in #792, this also adds similar tests for them, too.

Enhance UpdateSequence tests to verify create and update timestamps.

---

cmd/registry/cmd/upload/csv.go

This was our last remaining unconfigurable worker queue. Closes #154.

Add --jobs flag to `registry upload csv`

---

cmd/registry/controller/controller.go
cmd/registry/controller/list.go
cmd/registry/patterns/resources.go
cmd/registry/scoring/score_test.go
cmd/registry/scoring/scorecard_test.go
cmd/registry/scoring/scoring-timestamp_test.go

This the preparation for enabling the following feature in the scoring tool:
Currently, a score can be derived only from the artifacts that are attached to the primary entities (apis, versions, specs, deployments). However, we would also like the ability to derive a score from the primary entity itself, an example of this is the completeness score for an API, how well hydrated (with information) is a particular API stored in the registry.

Add the original resource to patterns.ResourceInstance

---

examples/grpc-client/main.go
pkg/connection/client.go

with `grpc.WithTransportCredentials(insecure.NewCredentials())`
https://stackoverflow.com/a/70482635
This is one of two fixes required to address #843

Replace deprecated `grpc.WithInsecure()`

---

pkg/connection/client.go

Fixes #853
Ultimate error message:
```
FATAL[0000] Failed to get client      error=registry token missing, attempted gcloud credentials: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information. uid=a2921302
```

better error message when missing token

---

cmd/registry/cmd/compute/vocabulary.go

With this change, a single failure won't abort all other work.
See #870 for context.

Use WorkerPoolWithWarnings in vocabulary calculations

---

cmd/registry/core/print.go
cmd/registry/patch/patch_test.go
cmd/registry/patch/testdata/artifacts/displaysettings.yaml
cmd/registry/patch/testdata/artifacts/extensions.yaml
cmd/registry/patch/testdata/artifacts/lifecycle.yaml
cmd/registry/patch/testdata/artifacts/manifest.yaml
cmd/registry/patch/testdata/artifacts/references.yaml
cmd/registry/patch/testdata/artifacts/styleguide.yaml
cmd/registry/patch/testdata/artifacts/taxonomies.yaml

This adds tests for seven more artifact types: ApiSpecExtensions, DisplaySettings, Lifecycle, Manifest, ReferenceLists, StyleGuides, and TaxonomyLists. Test configurations now allow a `parent` to be specified that can be any valid artifact parent - this must match the `parent` field in the artifact YAML.

Add tests for additional artifact YAML I/O.

---

.github/workflows/go.yml
cmd/registry/controller/local-tasks.go
pkg/connection/grpctest/server.go

Fixes #864 by using a configuration override instead of environment variables.
One glitch noted in #864 was that the controller invokes a separate executable of the registry tool. To configure that invocation to use the test server, this adds flags to the invocation so that it will use `address` and `insecure` settings that match the calling tool.

Remove environment variable-based configuration from tests.

---

cmd/registry/cmd/upload/bulk/protos.go
cmd/registry/cmd/upload/bulk/protos_test.go
cmd/registry/cmd/upload/spec.go
demos/protos.sh

Remove ".zip" extension from spec ids created by uploaders.

---

cmd/registry/cmd/upload/bulk/openapi.go
cmd/registry/cmd/upload/bulk/openapi_test.go
demos/openapi.sh

Closes #865.
This only updates the bulk uploader, related tests, and the demo script that depends on the bulk uploader.
Numerous tests use `openapi.yaml` as a spec ID. I think updating these would obscure the change in this PR and also that updating these tests is not particularly urgent since the ids are isolated within the tests. If that seems ok, I'll create a followup PR to update the tests.

Always use "openapi" as the spec id for bulk-uploaded openapi specs.

---

cmd/registry/cmd/upload/bulk/discovery.go
cmd/registry/cmd/upload/bulk/discovery_test.go
cmd/registry/cmd/upload/bulk/testdata/discovery/apigeeregistry-v1.json
cmd/registry/cmd/upload/bulk/testdata/discovery/apis.json
cmd/registry/cmd/upload/bulk/testdata/discovery/discovery-v1.json

Completes #739. The Discovery Service is easy to mock - here we just serve static files from the `testdata/discovery` directory.

Test discovery bulk uploads with a local mock server.

---

gapic/admin_client.go
gapic/admin_client_example_test.go
gapic/doc.go
gapic/grpc_service_config.json
gapic/provisioning_client.go
gapic/provisioning_client_example_test.go
gapic/registry_client.go
gapic/registry_client_example_test.go

This works around some issues that we're seeing in hosted implementations which cause API calls to be cancelled prematurely. Proxies are subtracting time from the deadlines that we send and cancelling if the remaining time is less than some threshold. Specifically, we see our 20s timeout become 10s, and then with a fraction of a second removed during processing, the operation is canceled because the hosting platform requires 10s minimums. This seems like a bug in the hosting configuration, so we might revisit this when that's better understood.
See also: https://github.com/googleapis/gapic-generator-go/issues/1206

Increase gRPC client timeout to 60 seconds

---

server/registry/names/deployment_revision.go
server/registry/names/names_test.go
server/registry/names/spec_revision.go

Patterns used to match spec and deployment revision collections were breaking changes that I was testing for #896. Here's the fix in a standalone PR.

Fix patterns for revision collection names.

---

cmd/registry/main.go

Prior to this change, errors were being printed twice by the `registry tool`: once by the Cobra framework and once by our code (which this PR deletes).
```
$ registry get invalid
Error: unsupported entity projects/googleapis/locations/global/invalid
Usage:
registry get PATTERN [flags]
Flags:
--filter string   Filter selected resources
-h, --help            help for get
-o, --output string   Output type (name, yaml, contents) (default "name")
Global Flags:
-c, --config string              name of a configuration profile or path to config file
--registry.address string    the server and port of the registry api (eg. localhost:8080)
--registry.insecure          if specified, client connects via http (not https)
--registry.location string   the registry location
--registry.project string …
```

Remove redundant print of errors - cobra prints errors so we don't need to

---

cmd/registry/cmd/get/get.go

Minor tweak to errors returned by `registry get` for invalid patterns. Instead of saying "unsupported entity" we say "unsupported pattern".

Update `registry get` errors to "unsupported pattern"

---

cmd/registry/cmd/check/lint/checker.go
cmd/registry/cmd/check/lint/checker_test.go
cmd/registry/cmd/check/lint/config.go
cmd/registry/cmd/check/lint/config_test.go
cmd/registry/cmd/check/lint/problem.go
cmd/registry/cmd/check/lint/problem_test.go
cmd/registry/cmd/check/lint/response.go
cmd/registry/cmd/check/lint/rule.go
cmd/registry/cmd/check/lint/rule_name.go
cmd/registry/cmd/check/lint/rule_name_test.go
cmd/registry/cmd/check/lint/rule_registry.go
cmd/registry/cmd/check/lint/rule_registry_test.go
cmd/registry/cmd/check/lint/rule_test.go
cmd/registry/cmd/check/lint/task.go
cmd/registry/cmd/check/rules/rules.go
config/registry-server.yaml
deployments/envoy/envoy-auth.yaml
deployments/envoy/envoy-noauth.yaml
deployments/envoy/envoy.yaml
deployments/envoy/envoy.yaml.tmpl

Fixes #937
Note: some generated gapic files still use `https` in their notices, these were not touched.

fix apache copyright notices

---

cmd/registry/patch/patch_test.go
cmd/registry/patch/testdata/artifacts/receipt.yaml
cmd/registry/types/types.go
cmd/registry/types/types_test.go

While running `registry export` on a project with a manifest, I noticed that we were logging warnings because receipts couldn't be exported. This registers the receipt type with the `registry` tool to allow it to be handled like other artifacts.

Add support for exporting, getting, and applying receipts in YAML.

---

server/registry/names/api_test.go
server/registry/names/artifact_test.go
server/registry/names/common.go
server/registry/names/deployment_revision_test.go
server/registry/names/deployment_test.go
server/registry/names/names_test.go
server/registry/names/project_test.go
server/registry/names/spec_revision_test.go
server/registry/names/spec_test.go
server/registry/names/version_test.go

I think this gets close enough to close #911.
Uncovered code appears to be unreachable.
Tests could be better (not all failures are clearly explained), but since the `names` package is so simple, I think it's better to not overinvest in this and leave further test improvement for when/if it's needed.

Add tests for `names` package.

---

cmd/registry/cmd/check/lint/checker.go
cmd/registry/cmd/check/lint/checker_test.go
pkg/connection/grpctest/server.go

refactor test setup and seeding to be reusable
add accessor for registryClient
fix ioutil deprecation warning
I broke this refactor out to be more easily reviewed, I use it in my testing PR that will come next.

refactor test setup and seeding to be reusable

---

cmd/registry/main.go

Example:
```
➜  registry git:(main) ✗ registry get apis -x
Error: unknown shorthand flag: 'x' in -x
Usage:
registry get PATTERN [flags]
Flags:
--filter string   filter selected resources
-h, --help            help for get
-o, --output string   output type (name|yaml|contents) (default "name")
Global Flags:
-c, --config string              name of a configuration profile or path to config file
--registry.address string    the server and port of the Registry API (eg. localhost:8080)
--registry.insecure          if specified, client connects via http (not https)
--registry.location string   the API Registry location
--registry.project string    the API Registry project
--registry.token string      the token to use for authorization to the API Registry
----
Need more help? …
```

emit wiki link when user gets an error in the CLI

---

cmd/registry/cmd/delete/delete.go
cmd/registry/cmd/export/export.go
cmd/registry/cmd/get/get.go
cmd/registry/core/get.go
cmd/registry/patch/patch_test.go

We've observed that `registry export projects/PROJECT` fails to export hosted PROJECT instances, because these lack the Admin service. This modifies the `core.GetProject()` helper to optionally provide dummy projects when the Admin service is unavailable. This is limited to `registry export`, which will fail subsequently if a nonexistent project is provided. `registry get` and `registry delete` will continue to fail for hosted project because these operations don't make sense for hosted projects (deleting an entire project is conceivable but is not something that we should support in this way).
Exporting an existing project now just works:
```
$ registry export projects/timburks-test
INFO[0001] Exported projects/timburks-test/locations/global/apis/apigeeregistry uid=916c601f
INFO[0001] …
```

Allow hosted projects to be exported with `registry export`

---

cmd/registry/cmd/upload/csv.go
cmd/registry/cmd/upload/csv_test.go

This addresses #971 by using [core.VerifyLocation()](https://github.com/apigee/registry/blob/989942a561d89fd1f51ec1bdca34b496899be252/cmd/registry/core/verify.go#L10) instead of the Admin service to verify that a parent project exists.
Other incidental changes:
- `upload csv` no longer creates projects on demand, as with other uploaders, destination projects must be preexisting.
- this addresses #827 by converting the `upload csv` command to use `RunE` and return errors instead of logging fatal errors.
- the `--parent` flag is used instead of `--project_id` and is processed by a common function used by other `upload` commands.
- Names are used instead of strings in the command implementation.
(new tests for error cases are coming to this PR)

Allow uploads of CSV to hosted registries.

---

auth/HOSTED.sh

Closed original #967  due to not having signed the CLA.
The existing way had two different env variables and `gcloud config get account` doesn't just print the email it also includes the project:
```
$ gcloud config get account                                                                                                                                                           ─╯
$ Your active configuration is: [api-registry]
$ john@smith.com
```
```
$ gcloud config list account --format "value(core.account)"
$ john@smith.com
```
I believe you want the latter?!

Bugfix for getting current user email

---

cmd/registry/cmd/compute/complexity/complexity-discovery.go
cmd/registry/cmd/compute/complexity/complexity-openapi.go
cmd/registry/cmd/compute/complexity/complexity-proto.go
cmd/registry/cmd/compute/complexity/complexity.go
cmd/registry/cmd/compute/complexity/complexity_test.go
cmd/registry/cmd/compute/complexity_test.go
cmd/registry/cmd/compute/compute.go
cmd/registry/cmd/compute/compute_test.go
cmd/registry/cmd/compute/conformance/conformance.go
cmd/registry/cmd/compute/conformance/conformance_test.go
cmd/registry/cmd/compute/lint/lint-openapi-gnostic.go
cmd/registry/cmd/compute/lint/lint-openapi-spectral.go
cmd/registry/cmd/compute/lint/lint-openapi.go
cmd/registry/cmd/compute/lint/lint-proto.go
cmd/registry/cmd/compute/lint/lint.go
cmd/registry/cmd/compute/lint/lint_test.go
cmd/registry/cmd/compute/lintstats/lintstats.go
cmd/registry/cmd/compute/lintstats/lintstats_test.go
cmd/registry/cmd/compute/score/score.go
cmd/registry/cmd/compute/score/score_test.go
cmd/registry/cmd/compute/scorecard/scorecard.go
cmd/registry/cmd/compute/scorecard/scorecard_test.go
cmd/registry/cmd/compute/vocabulary/vocabulary-proto.go
cmd/registry/cmd/compute/vocabulary/vocabulary.go
cmd/registry/cmd/compute/vocabulary/vocabulary_test.go

Addresses #944 by pushing `registry compute` subcommand implementations into separate directories that can be independently prioritized for test coverage. Three subcommands were untested, so to keep them in our coverage stats, I added stub tests in each three that just verify that a command that is run without arguments returns an error.
The division causes some code to be duplicated that was previously shared in the `compute` package. I don't think it's significant, and would like to leave it to be addressed in any future refactoring of the tests that aims to reduce duplication (I don't think this is currently a priority). Also, flag declarations are pushed down to the leaf level because they are needed in leaf-level tests (and including the `compute` package creates an import cycle). …

Push subcommands of `registry compute` into separate directories.

---

cmd/registry/cmd/delete/delete.go
cmd/registry/cmd/export/export.go
cmd/registry/cmd/get/get.go
cmd/registry/core/visitors.go

This defines a new `Visitor` interface and a `Visit` function that applies the visitor to resources matching a pattern and filter. This was factored out of the `registry get`, `registry export`, and `registry delete` commands. It builds on the `List*` and `Get*` functions in `core` without making any changes to those. The `Visitor` interface returns closures that are passed to these functions. If usage expands, I think we might consider new `List` and `Get` methods that just take `Visitor` instances and call appropriate functions in the interface - then the `Visitor` interface would just be handlers and not need to return closures. But this seems like a good incremental step forward.
Note that there are some contexts in structs pending #913.
Looking ahead to testing, I think this and …

Factor a "visitors" pattern out of the get/delete/export implementations.

---

cmd/registry/README.md
cmd/registry/cmd/apply/apply.go
cmd/registry/cmd/root_test.go
cmd/registry/patch/api.go
cmd/registry/patch/apply.go
cmd/registry/patch/artifact.go
cmd/registry/patch/deployment.go
cmd/registry/patch/spec.go
cmd/registry/patch/version.go

This PR adds information to docs, error messages, info logs, and other sources of information for users of `registry apply`. It addresses some of the issues/confusion that led to #984.
Although it adds validation checks that return errors, those errors should only be returned in situations where an error would have occurred anyway. Anything that worked before should still work now. For example, when the `-f` flag isn't provided, or when `metadata.parent` isn't provided for a resource that isn't top-level, we return a more informative error.
Similarly, anything that returned an error before, should still return an error now. The only exception is the `--parent` flag can now accept project names without a location, e.g. `projects/my-project` will default to the global location …

Additional usage information for `registry apply`

---

cmd/registry/cmd/annotate/annotate.go
cmd/registry/cmd/label/label.go
cmd/registry/cmd/label/labeling.go

move "labeling.go" helpers from core to cmd/label.

---

cmd/registry/cmd/annotate/annotate.go
cmd/registry/cmd/check/lint/checker.go
cmd/registry/cmd/compute/complexity/complexity.go
cmd/registry/cmd/compute/conformance/conformance.go
cmd/registry/cmd/compute/lint/lint.go
cmd/registry/cmd/compute/score/score.go
cmd/registry/cmd/compute/scorecard/scorecard.go
cmd/registry/cmd/compute/vocabulary/vocabulary.go
cmd/registry/cmd/delete/delete.go
cmd/registry/cmd/export/export.go
cmd/registry/cmd/label/label.go
cmd/registry/cmd/resolve/resolve.go
cmd/registry/cmd/upload/csv.go
cmd/registry/cmd/upload/discovery.go
cmd/registry/cmd/upload/openapi.go
cmd/registry/cmd/upload/protos.go
cmd/registry/patch/apply.go
cmd/registry/patch/export_test.go
cmd/registry/patch/project.go
cmd/registry/tasks/tasks.go
cmd/registry/tasks/tasks_test.go
pkg/wipeout/wipeout.go

Also for #1007, this moves tasks.go into a dedicated package. 
(We need #917 so that we can get rid of those logging statements)

move core/tasks.go to tasks/tasks.go

---

cmd/registry/cmd/get/get.go
cmd/registry/cmd/get/get_test.go

Closes #1024
This adds support for `--output raw` (`-o raw`) to `registry get` and returns a JSON array of the raw message content of matching resources. Because `registry get` can return multiple values and to simplify downstream processing of the resulting JSON, results are always returned as a JSON array.
Here are some thoughts on using `raw` as the option name:
- It's a direct (JSON) representation of the API message and matches what is returned by the generated `rpc` commands.
- It is not `--output json` because I think we should save that for a JSON-equivalent of Registry YAML.
- It is not `--output message` because I think that would suggest results were the encoded protobuf messages.

Add `-o raw` support to `registry get`.

---

cmd/registry/cmd/compute/conformance/conformance_test.go
cmd/registry/cmd/compute/score/score_test.go
cmd/registry/cmd/compute/scorecard/scorecard_test.go
cmd/registry/cmd/resolve/resolve_test.go
cmd/registry/cmd/upload/csv_test.go
cmd/registry/cmd/upload/testdata/csv/multiple-specs.csv
cmd/registry/cmd/upload/testdata/csv/out-of-order-columns.csv
cmd/registry/cmd/upload/testdata/discovery/apigeeregistry-v1.json
cmd/registry/cmd/upload/testdata/protos/google/cloud/apigeeregistry/v1/registry_service.proto
cmd/registry/conformance/conformance-task.go
cmd/registry/conformance/conformance-task_test.go
cmd/registry/controller/controller-error-path_test.go
cmd/registry/controller/controller-timestamp_test.go
cmd/registry/controller/controller_test.go
cmd/registry/controller/parser_test.go
cmd/registry/patch/patch_test.go
cmd/registry/patch/testdata/artifacts/conformancereport.yaml
cmd/registry/patterns/parser.go
cmd/registry/patterns/parser_test.go
cmd/registry/patterns/resources.go
cmd/registry/scoring/parser_test.go
cmd/registry/scoring/score_test.go
cmd/registry/scoring/scorecard_test.go
cmd/registry/scoring/scoring-timestamp_test.go
google/cloud/apigeeregistry/v1/registry_service.proto
pkg/names/names_test.go
rpc/registry_service.pb.go
tests/crud/crud_test.go
tests/demo/demo_test.go
tests/demo/walkthrough.sh

Fixes #883 by replacing "openapi.yaml" spec IDs with "openapi" in all tests. This follows #882 which removed extensions from IDs created by the bulk importers. Generally we want to discourage the use of extensions in resource ids so that YAML exports can use resource ids as names of directories; these directories contain resource details and children.
This change exposed #1023 by breaking the `registry compute conformance` tests. The problem was that the conformance task-runner was writing specs into files named by their spec id, and lint runners were expecting linted files to have ".yaml" extensions, so the linting skipped them. This PR doesn't change the lint runners (they still expect ".yaml" extensions), but changes the task-runner to name spec files using their specified `filename` …

Remove ".yaml" extensions from all spec ids used in tests.

---

cmd/registry/patch/api.go
cmd/registry/patch/apply.go
cmd/registry/patch/artifact.go
cmd/registry/patch/deployment.go
cmd/registry/patch/patch_test.go
cmd/registry/patch/spec.go
cmd/registry/patch/version.go

When `registry apply` uploads spec files, it looks for them in the same directory as the YAML file that referenced them, i.e. the specs should be alongside the YAML. This requires us to pass the path to the containing YAML file all the way down to the spec handler. Previously YAML representations of specs were getting the path name, but higher-level nested representations (APIs and versions) did not have their filenames passed down during processing. This fixes that and passes the containing filename down to all handlers, including artifact handlers, which don't need them now but would use them if/when we support importing external (binary?) files as artifact contents.

Pass filenames of patch files to all patch helpers.

---

cmd/registry/cmd/apply/apply.go
cmd/registry/cmd/apply/apply_test.go
cmd/registry/patch/apply.go
cmd/registry/patch/export_test.go
cmd/registry/patch/patch_lists_test.go
cmd/registry/patch/patch_project_test.go
cmd/registry/patch/patch_test.go
cmd/registry/patch/testdata/empty/README.md

Fixes #889 
`registry apply` now reports the number of files read and applied. 
For a moderate-sized input, the final log message looks like this:
```
INFO[0002] 44 YAML file(s) applied (87 found, 44 with 'apiVersion: apigeeregistry/v1') uid=79eb00e5
```
For a single file input, the log message looks like this:
```
INFO[0000] 1 YAML file(s) applied (1 found, 1 with 'apiVersion: apigeeregistry/v1') uid=f7bc2216
```
Errors are reported if a directory is specified that contains no YAML files:
```
Error: no YAML files found
```
Errors are also reported if none of the YAML files found are valid Registry YAML:
```
Error: no YAML files applied (1 found, none with 'apiVersion: apigeeregistry/v1')
```

Add improved error reporting to `registry apply`.

---

README.md
cmd/registry/README.md
downloadLatest.sh

Fixes #1043, but this only installs `registry`. We will probably also want to install the linter plugins, but these currently aren't included in release builds.

Add a script that installs the latest release of the registry tool.

---

downloadLatest.sh

Running the latest download script with `v0.6.6`, I get the following error on Linux:
```
$ sh downloadLatest.sh 
https://github.com/apigee/registry/releases/download/v0.6.6/registry_0.6.6_linux_amd64.tar.gz
Downloading registry_v0.6.6 from https://github.com/apigee/registry/releases/download/v0.6.6/registry_0.6.6_linux_amd64.tar.gz ...
registry v0.6.6 Download Complete!
mv: cannot stat '/tmp/registry.PaMH31/registry-lint-*': No such file or directory
```
It appears that the globbing is not being expanded properly. This replaces the * with the specific filenames that we want to install.

Replace wildcards with specific file names in download script.

---

.github/workflows/docker-publish.yml

For your consideration: perhaps we do want to keep a nightly docker build around as we might want point users to it on occasion.

readd nightly build for docker

---

tests/benchmark/benchmark_apis_test.go
tests/benchmark/benchmark_artifacts_test.go
tests/benchmark/benchmark_helpers.go

This adds a benchmark test that lists artifacts under different resource types.
I've casually observed that listing artifacts under specs takes longer than listing artifacts under APIs, and guessed that this might be related to revision support. The test here creates N=100 APIs, each with one version, spec, and deployment, and with three artifacts ("a", "b", and "c") under each resource. Three revisions of each spec and deployment are created with artifacts only associated with the last ones created. Then we list all of the "b" artifacts under each resource type.
Running locally with Postgres on my Chromebook, I don't see much difference in listing times:
```
BenchmarkListArtifacts
BenchmarkListArtifacts/ListApiArtifacts
BenchmarkListArtifacts/ListApiArtifacts-8                     75 …
```

Add benchmark that lists artifacts under each resource type.

---

cmd/registry/cmd/rpc/rpc.go

Hiding these seemed to me to be a good idea (at the time), but now it seems to be more confusing to have hidden commands than to explain the differences between hosted and non-hosted installations.

Unhide generated rpc commands for Admin and Provisioning methods.

---

server/registry/internal/storage/models/deployment.go
server/registry/internal/storage/models/spec.go

Based on discussion in #1069, this adds indexes on the `ApiID` fields of specs and deployments.

Add indexes to specs and deployments.

---

cmd/registry/patch/deployment.go
cmd/registry/patch/patch_test.go
cmd/registry/patch/testdata/deployments-nested/registry.yaml
cmd/registry/patch/testdata/deployments-nested/separate-deployment.yaml

Fixes #1078 
tests are coming in this PR

Automatically infer latest spec revision when importing deployments

---

server/registry/internal/storage/list.go
server/registry/internal/storage/models/artifact.go

Fixes 1069
After using EXPLAIN, ANALYZE and doing additional research, I added an index and simplified our latest revision queries. Once done, I ran the benchmark with 100 iterations in a database that also held another project that held about 3500 APIs in it. The results are good all around, but are an especially significant improvement for artifacts.
Benchmark before:
```
BenchmarkGetApi/GetApi-10    	     100	    460169 ns/op
BenchmarkListApis/ListApis-10         	     100	   1497588 ns/op
BenchmarkCreateApi/CreateApi-10       	     100	    699478 ns/op
BenchmarkUpdateApi/UpdateApi-10       	     100	    847783 ns/op
BenchmarkDeleteApi/DeleteApi-10       	     100	   2851318 ns/op
BenchmarkListArtifacts/ListApiArtifacts-10         	     100	 155312918 ns/op …
```

optimize db: add index, rewrite query

---

cmd/registry/cmd/compute/vocabulary/testdata/apigeeregistry/v1/discovery/discovery.json
cmd/registry/cmd/compute/vocabulary/testdata/apigeeregistry/v1/discovery/info.yaml
cmd/registry/cmd/compute/vocabulary/testdata/apigeeregistry/v1/openapi/info.yaml
cmd/registry/cmd/compute/vocabulary/testdata/apigeeregistry/v1/openapi/openapi.yaml
cmd/registry/cmd/compute/vocabulary/vocabulary_test.go

These tests just verify that the command runs and computes something for these two spec types.

openapi and discovery-format tests for `registry compute vocabulary`

---

cmd/registry/cmd/compute/complexity/complexity_test.go
cmd/registry/cmd/compute/complexity/testdata/apigeeregistry/info.yaml
cmd/registry/cmd/compute/complexity/testdata/apigeeregistry/v1/discovery/discovery.json
cmd/registry/cmd/compute/complexity/testdata/apigeeregistry/v1/discovery/info.yaml
cmd/registry/cmd/compute/complexity/testdata/apigeeregistry/v1/info.yaml
cmd/registry/cmd/compute/complexity/testdata/apigeeregistry/v1/openapi/info.yaml
cmd/registry/cmd/compute/complexity/testdata/apigeeregistry/v1/openapi/openapi.yaml
cmd/registry/cmd/compute/complexity/testdata/apigeeregistry/v1/protos/google/api/annotations.proto
cmd/registry/cmd/compute/complexity/testdata/apigeeregistry/v1/protos/google/api/client.proto
cmd/registry/cmd/compute/complexity/testdata/apigeeregistry/v1/protos/google/api/field_behavior.proto
cmd/registry/cmd/compute/complexity/testdata/apigeeregistry/v1/protos/google/api/http.proto
cmd/registry/cmd/compute/complexity/testdata/apigeeregistry/v1/protos/google/api/httpbody.proto
cmd/registry/cmd/compute/complexity/testdata/apigeeregistry/v1/protos/google/api/launch_stage.proto
cmd/registry/cmd/compute/complexity/testdata/apigeeregistry/v1/protos/google/api/resource.proto
cmd/registry/cmd/compute/complexity/testdata/apigeeregistry/v1/protos/google/cloud/apigeeregistry/v1/apigeeregistry_v1.yaml
cmd/registry/cmd/compute/complexity/testdata/apigeeregistry/v1/protos/google/cloud/apigeeregistry/v1/provisioning_service.proto
cmd/registry/cmd/compute/complexity/testdata/apigeeregistry/v1/protos/google/cloud/apigeeregistry/v1/registry_models.proto
cmd/registry/cmd/compute/complexity/testdata/apigeeregistry/v1/protos/google/cloud/apigeeregistry/v1/registry_service.proto
cmd/registry/cmd/compute/complexity/testdata/apigeeregistry/v1/protos/google/longrunning/operations.proto
cmd/registry/cmd/compute/complexity/testdata/apigeeregistry/v1/protos/google/rpc/status.proto
cmd/registry/cmd/compute/complexity/testdata/apigeeregistry/v1/protos/info.yaml

This verifies that the computation runs and computes something for the three formats.
testdata is identical to the testdata in the vocabulary package, these could be merged and pulled up a level if desired.

Add basic tests of `registry compute complexity` for protos, openapi, and discovery formats

---

cmd/registry/cmd/compute/lint/lint.go

More is needed for `registry compute lint`, but this fixes a glaring problem in the mime type used to store lint artifacts, updating it to the correct current value.

Use correct mime type for lint artifacts.

---

cmd/registry/cmd/compute/complexity/complexity.go
cmd/registry/cmd/compute/lint/lint.go
cmd/registry/cmd/compute/vocabulary/vocabulary.go
cmd/registry/cmd/diff/diff.go
cmd/registry/cmd/get/get.go
cmd/registry/conformance/conformance-task.go
cmd/registry/patch/project.go
pkg/mime/types.go
pkg/mime/types_test.go
pkg/visitor/content.go
pkg/visitor/content_test.go
pkg/visitor/fetch.go
pkg/visitor/fetch_test.go
pkg/visitor/list.go

This fixes #1123 by modifying `visitor.GetSpecs` (and the underlying  `visitor.FetchSpecContents`) to always return ungzipped specs. To avoid confusing downstream code, this also modifies the mime type of the returned specs to match the unzipped content (i.e. the "+gzip" is removed). This might be seen as misrepresenting the content stored on the server, but overall I think this is better because downstream code often switches on spec mime types, and this avoids accidental double-uncompression.
Moving this uncompression into the `visitor` package allows us to eliminate uncompression throughout the registry tool subcommands. Now any client code that uses `visitor` can safely expect gzipped specs to be uncompressed.
With a few other small changes, this eliminates `visitor.GetSpecBytes()`, …

Automatically uncompress all spec data returned by the visitor package.

---

cmd/registry/cmd/annotate/annotate.go
cmd/registry/cmd/label/label.go

Progress towards #827. Remaining commands will be easier to change when #1129 is addressed.

Switch "registry annotate/label" to RunE

---

cmd/registry/cmd/compute/complexity/complexity.go
cmd/registry/cmd/compute/compute.go
cmd/registry/cmd/compute/conformance/conformance.go
cmd/registry/cmd/compute/lint/lint.go
cmd/registry/cmd/compute/lintstats/lintstats.go
cmd/registry/cmd/compute/score/score.go
cmd/registry/cmd/compute/scorecard/scorecard.go
cmd/registry/cmd/compute/vocabulary/vocabulary.go
cmd/registry/cmd/upload/csv.go
cmd/registry/cmd/upload/discovery.go
cmd/registry/cmd/upload/openapi.go
cmd/registry/cmd/upload/protos.go
cmd/registry/cmd/upload/upload.go
cmd/registry/cmd/upload/upload_test.go

Fixes #1129.
This converts everything except flags in automatically-generated CLI methods and `pkg/config`.

Convert registry tool flags to variable-bound.

---

cmd/registry/tasks/tasks_test.go

`TestWorkerPoolStopOnError` was intermittently failing with a count of 1000, which should be in the acceptable range.

Loosen test constraint (appropriately)

---

pkg/connection/config.go
pkg/connection/config_test.go

Use "global" as the default location when location is unspecified (i.e. empty).

---

.github/workflows/docker-publish.yml

Addresses [build warning](https://github.com/apigee/registry/actions/runs/4692896484):
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

update actions/checkout version

---

.github/actions/setup-registry/action.yml

Fixes #1149
Example for a local registry:
``` yaml
services:
local-registry:
image: ghcr.io/apigee/registry-server:main
env:
REGISTRY_LOGGING_LEVEL: debug
ports:
- 8080:8080
steps:
- name: Configure local Registry
uses: apigee/registry/.github/actions/registry-config
with:
name: local
address: localhost:8080
insecure: true
version: v0.6.10
project: test
- name: Create a project
run: registry rpc admin create-project --project_id test
```
Example for a remote registry:
``` yaml
- name: Set up Google Cloud auth
uses: google-github-actions/auth@v1
with:
credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
- name: Set up the Google Cloud SDK
uses: google-github-actions/setup-gcloud@v1
with:
skip_install: true
- name: Capture GOOGLE_CLOUD_PROJECT env var
run: echo …
```

github action to install and setup the registry cli tool

---

cmd/registry/cmd/compute/lint/lint.go

add debug flag that retains temporary files

---

cmd/registry/main.go

Fixes #1154
Adds list of plugins to usage page and allows execution of these directly in registry command. Also moves `Need more help?` wiki link direclty into usage template. See below.
This is a very basic implementation in that it only looks for `registry-*` filenames on the path and doesn't have any information about the plugins. 
But give it a try and see what you think.
```
$ registry -h
A command-line tool for working with the API Registry
Usage:
registry [command]
Available Commands:
annotate    Annotate resources in the API Registry
apply       Apply YAML to the API Registry
auth        Manage authentication to the API Registry
check       Check entities in the API Registry
completion  Generate the autocompletion script for the specified shell
compute     Compute properties of …
```

show available plugins in registry cli

---

cmd/registry/cmd/check/rules/rule1000/rule1000.go
cmd/registry/cmd/check/rules/rule1001/rule1001.go
cmd/registry/cmd/check/rules/rule1002/rule1002.go
cmd/registry/cmd/check/rules/rule1003/rule1003.go
cmd/registry/cmd/compute/complexity/complexity_test.go
cmd/registry/cmd/compute/conformance/conformance.go
cmd/registry/cmd/compute/conformance/conformance_test.go
cmd/registry/cmd/compute/lint/lint_test.go
cmd/registry/cmd/compute/lintstats/lintstats.go
cmd/registry/cmd/compute/score/score.go
cmd/registry/cmd/compute/scorecard/scorecard.go
cmd/registry/cmd/compute/vocabulary/vocabulary_test.go
cmd/registry/cmd/resolve/resolve.go
cmd/registry/patch/artifact.go
cmd/registry/patch/patch_test.go
cmd/registry/scoring/expression.go
cmd/registry/scoring/score.go
cmd/registry/scoring/score_test.go
cmd/registry/scoring/scorecard.go
cmd/registry/scoring/scorecard_test.go
cmd/registry/scoring/scoring-timestamp_test.go
pkg/mime/types.go

Task 2 in #946: Update registry subcommands that read artifacts to support both serialized protos and YAML.

support both serialized protos and YAML

---

cmd/registry/main.go

Only print Available Plugins when the list is not empty.

---

cmd/registry/main.go

Produces:
```
$ registry
A command-line tool for working with the API Registry
Usage:
registry [command]
Available Commands:
annotate    Annotate resources in the API Registry
apply       Apply YAML to the API Registry
auth        Manage authentication to the API Registry
check       Check entities in the API Registry
completion  Generate the autocompletion script for the specified shell
compute     Compute properties of resources in the API Registry
config      Maintain properties in the active configuration
delete      Delete resources from the API Registry
diff        Compare resources in the API Registry
export      Export resources from the API Registry
get         Get resources from the API Registry
help        Help about any command
label       Label resources in the API Registry …
```

Indent usage string, available commands, and available plugins

---

server/registry/actions_apis.go
server/registry/actions_apis_test.go
server/registry/actions_artifacts.go
server/registry/actions_artifacts_test.go
server/registry/actions_deployments.go
server/registry/actions_deployments_test.go
server/registry/actions_projects.go
server/registry/actions_projects_test.go
server/registry/actions_specs.go
server/registry/actions_specs_test.go
server/registry/actions_versions.go
server/registry/actions_versions_test.go

Allow nil when creating:
* apis
* artifacts
* deployments
* projects
* specs
* versions
Fixes #1198

allow nil bodies in create resource endpoints

---

cmd/registry-server/main.go

Fixes an issue with https://github.com/apigee/registry/pull/1207 where --no-migrate flag meaning was reversed.

migrate should run without --no-migrate flag

---

cmd/registry/cmd/annotate/annotate.go
cmd/registry/cmd/check/rules/rule1000/rule1000.go
cmd/registry/cmd/compute/complexity/complexity.go
cmd/registry/cmd/compute/conformance/conformance.go
cmd/registry/cmd/compute/lint/lint.go
cmd/registry/cmd/compute/lintstats/lintstats.go
cmd/registry/cmd/compute/vocabulary/vocabulary.go
cmd/registry/cmd/get/get.go
cmd/registry/cmd/label/label.go
cmd/registry/controller/list.go
cmd/registry/patch/api.go
cmd/registry/patch/project.go
cmd/registry/patch/version.go
cmd/registry/patterns/resources.go
cmd/registry/scoring/artifact-client.go
pkg/visitor/fetch_test.go
pkg/visitor/list.go
pkg/visitor/subtree.go
pkg/visitor/visit.go
server/registry/internal/storage/models/deployment.go

* added index to deployments
* added page size to visitors
* changed `registry get` page size to 1k
* fixed missed filter passing in visitors where found
Fixes #1208

improve deployment query performance

---

pkg/visitor/list.go

This fixes a problem that @theganyo discovered in which calls to hosted versions of the `ListApiSpecRevisions` and `ListApiDeploymentRevisions` failed when `@-` was appended to the resource names. These suffixes were being included in the [name](https://github.com/apigee/registry/blob/bce42327880e246c3d71072ce3481084b43aa8f4/google/cloud/apigeeregistry/v1/registry_service.proto#L793) arguments, which is strictly expected to be a resource name (and not a pattern that matches collections). The core implementation accidentally supports these modified names, but hosted implementations may not, because it is out of spec, and agreeing with that, we trim the `@-` from these names before passing them as arguments.
This is a Postel's Law solution -- the `visitor` package is now conservative in the …

Trim the "@-" suffix from resource names before calling the List*Revisions APIs.

---

.github/workflows/snyk.yml

Add workflow to run snyk scan following Snyk documentation: https://docs.snyk.io/integrations/snyk-ci-cd-integrations/github-actions-integration/snyk-golang-action.
This workflow can be run manually and will automatically run once a week Sunday night. For now, this is just configured to run `snyk test` - https://docs.snyk.io/snyk-cli/commands/test. This will scan the repo for vulnerability and license issues and the cli will exit with 1 if any are found.
An example run is here: https://github.com/hansatgoogle/registry/actions/runs/6123960183/job/16622986936. As you can see, this currently finds an issue with a MPL-2.0 license. I don't think that's a concern for us as we aren't likely to modify that library. To get this scan to pass, we could create a custom license policy in snyk …

Add snyk scan workflow

---

pkg/config/config.go
pkg/config/configuration_test.go

Fix problems with reading config files using `--config`

---

pkg/config/config.go
pkg/config/configuration_test.go
pkg/connection/config.go

Fixes #1231
`config.Active()` [supports the `--config` flag](https://github.com/timburks/registry/blob/d0fe7e5d450b2f71fbaf1e24d62cea244928cfba/pkg/config/config.go#L115) where the previous code for `connection.ActiveConfig()` does not.

connection.ActiveConfig() should use config.Active() instead of reading configuration directly
